module Evergreen.Migrate.V102 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V102.Id
import Evergreen.V102.Name
import Evergreen.V102.PurchaseForm
import Evergreen.V102.Route
import Evergreen.V102.Stripe
import Evergreen.V102.TravelMode
import Evergreen.V102.Types
import Evergreen.V97.Id
import Evergreen.V97.Name
import Evergreen.V97.PurchaseForm
import Evergreen.V97.Route
import Evergreen.V97.Stripe
import Evergreen.V97.TravelMode
import Evergreen.V97.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import SeqDict


frontendModel : Evergreen.V97.Types.FrontendModel -> ModelMigration Evergreen.V102.Types.FrontendModel Evergreen.V102.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V97.Types.BackendModel -> ModelMigration Evergreen.V102.Types.BackendModel Evergreen.V102.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V97.Types.FrontendMsg -> MsgMigration Evergreen.V102.Types.FrontendMsg Evergreen.V102.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V97.Types.ToBackend -> MsgMigration Evergreen.V102.Types.ToBackend Evergreen.V102.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V97.Types.BackendMsg -> MsgMigration Evergreen.V102.Types.BackendMsg Evergreen.V102.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V97.Types.ToFrontend -> MsgMigration Evergreen.V102.Types.ToFrontend Evergreen.V102.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Id_Id : Evergreen.V97.Id.Id a_old -> Evergreen.V102.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V97.Id.Id p0 ->
            Evergreen.V102.Id.Id p0


migrate_Name_Name : Evergreen.V97.Name.Name -> Evergreen.V102.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V97.Name.Name p0 ->
            Evergreen.V102.Name.Name p0


migrate_PurchaseForm_Accommodation : Evergreen.V97.PurchaseForm.Accommodation -> Evergreen.V102.PurchaseForm.Accommodation
migrate_PurchaseForm_Accommodation old =
    case old of
        Evergreen.V97.PurchaseForm.Offsite ->
            Evergreen.V102.PurchaseForm.Offsite

        Evergreen.V97.PurchaseForm.Campsite ->
            Evergreen.V102.PurchaseForm.Campsite

        Evergreen.V97.PurchaseForm.Single ->
            Evergreen.V102.PurchaseForm.Single

        Evergreen.V97.PurchaseForm.Double ->
            Evergreen.V102.PurchaseForm.Double

        Evergreen.V97.PurchaseForm.Group ->
            Evergreen.V102.PurchaseForm.Group


migrate_PurchaseForm_AttendeeForm : Evergreen.V97.PurchaseForm.AttendeeForm -> Evergreen.V102.PurchaseForm.AttendeeForm
migrate_PurchaseForm_AttendeeForm old =
    { name = old.name
    , email = old.email
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> Maybe.map migrate_TravelMode_TravelMode
    }


migrate_PurchaseForm_AttendeeFormValidated : Evergreen.V97.PurchaseForm.AttendeeFormValidated -> Evergreen.V102.PurchaseForm.AttendeeFormValidated
migrate_PurchaseForm_AttendeeFormValidated old =
    { name = old.name |> migrate_Name_Name
    , email = old.email
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> Maybe.map migrate_TravelMode_TravelMode
    }


migrate_PurchaseForm_PressedSubmit : Evergreen.V97.PurchaseForm.PressedSubmit -> Evergreen.V102.PurchaseForm.PressedSubmit
migrate_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V97.PurchaseForm.PressedSubmit ->
            Evergreen.V102.PurchaseForm.PressedSubmit

        Evergreen.V97.PurchaseForm.NotPressedSubmit ->
            Evergreen.V102.PurchaseForm.NotPressedSubmit


migrate_PurchaseForm_PurchaseForm : Evergreen.V97.PurchaseForm.PurchaseForm -> Evergreen.V102.PurchaseForm.PurchaseForm
migrate_PurchaseForm_PurchaseForm old =
    { submitStatus = old.submitStatus |> migrate_PurchaseForm_SubmitStatus
    , attendees = old.attendees |> List.map migrate_PurchaseForm_AttendeeForm
    , accommodationBookings = old.accommodationBookings |> List.map migrate_PurchaseForm_Accommodation
    , billingEmail = old.billingEmail
    , grantContribution = old.grantContribution
    , grantApply = old.grantApply
    , sponsorship = old.sponsorship
    }


migrate_PurchaseForm_PurchaseFormValidated : Evergreen.V97.PurchaseForm.PurchaseFormValidated -> Evergreen.V102.PurchaseForm.PurchaseFormValidated
migrate_PurchaseForm_PurchaseFormValidated old =
    { attendees = old.attendees |> List.map migrate_PurchaseForm_AttendeeFormValidated
    , accommodationBookings = old.accommodationBookings |> List.map migrate_PurchaseForm_Accommodation
    , billingEmail = old.billingEmail
    , grantContribution = old.grantContribution
    , grantApply = old.grantApply
    , sponsorship = old.sponsorship
    }


migrate_PurchaseForm_SubmitStatus : Evergreen.V97.PurchaseForm.SubmitStatus -> Evergreen.V102.PurchaseForm.SubmitStatus
migrate_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V97.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V102.PurchaseForm.NotSubmitted (p0 |> migrate_PurchaseForm_PressedSubmit)

        Evergreen.V97.PurchaseForm.Submitting ->
            Evergreen.V102.PurchaseForm.Submitting

        Evergreen.V97.PurchaseForm.SubmitBackendError p0 ->
            Evergreen.V102.PurchaseForm.SubmitBackendError p0


migrate_Route_Route : Evergreen.V97.Route.Route -> Evergreen.V102.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V97.Route.HomepageRoute ->
            Evergreen.V102.Route.HomepageRoute

        Evergreen.V97.Route.UnconferenceFormatRoute ->
            Evergreen.V102.Route.UnconferenceFormatRoute

        Evergreen.V97.Route.VenueAndAccessRoute ->
            Evergreen.V102.Route.VenueAndAccessRoute

        Evergreen.V97.Route.CodeOfConductRoute ->
            Evergreen.V102.Route.CodeOfConductRoute

        Evergreen.V97.Route.OrganisersRoute ->
            Evergreen.V102.Route.OrganisersRoute

        Evergreen.V97.Route.ElmCampArchiveRoute ->
            Evergreen.V102.Route.ElmCampArchiveRoute

        Evergreen.V97.Route.AdminRoute p0 ->
            Evergreen.V102.Route.AdminRoute p0

        Evergreen.V97.Route.PaymentSuccessRoute p0 ->
            Evergreen.V102.Route.PaymentSuccessRoute p0

        Evergreen.V97.Route.PaymentCancelRoute ->
            Evergreen.V102.Route.PaymentCancelRoute

        Evergreen.V97.Route.Camp23Denmark p0 ->
            Evergreen.V102.Route.Camp23Denmark (p0 |> migrate_Route_SubPage)

        Evergreen.V97.Route.Camp24Uk p0 ->
            Evergreen.V102.Route.Camp24Uk (p0 |> migrate_Route_SubPage)

        Evergreen.V97.Route.Camp25US p0 ->
            Evergreen.V102.Route.Camp25US (p0 |> migrate_Route_SubPage)

        Evergreen.V97.Route.Camp26Czech p0 ->
            Evergreen.V102.Route.Camp26Czech (p0 |> migrate_Route_SubPage)


migrate_Route_SubPage : Evergreen.V97.Route.SubPage -> Evergreen.V102.Route.SubPage
migrate_Route_SubPage old =
    case old of
        Evergreen.V97.Route.Home ->
            Evergreen.V102.Route.Home

        Evergreen.V97.Route.Artifacts ->
            Evergreen.V102.Route.Artifacts


migrate_Stripe_Price : Evergreen.V97.Stripe.Price -> Evergreen.V102.Stripe.Price
migrate_Stripe_Price old =
    old


migrate_TravelMode_TravelMode : Evergreen.V97.TravelMode.TravelMode -> Evergreen.V102.TravelMode.TravelMode
migrate_TravelMode_TravelMode old =
    case old of
        Evergreen.V97.TravelMode.Flight ->
            Evergreen.V102.TravelMode.Flight

        Evergreen.V97.TravelMode.Bus ->
            Evergreen.V102.TravelMode.Bus

        Evergreen.V97.TravelMode.Car ->
            Evergreen.V102.TravelMode.Car

        Evergreen.V97.TravelMode.Train ->
            Evergreen.V102.TravelMode.Train

        Evergreen.V97.TravelMode.Boat ->
            Evergreen.V102.TravelMode.Boat

        Evergreen.V97.TravelMode.OtherTravelMode ->
            Evergreen.V102.TravelMode.OtherTravelMode


migrate_Types_BackendModel : Evergreen.V97.Types.BackendModel -> Evergreen.V102.Types.BackendModel
migrate_Types_BackendModel old =
    { orders = old.orders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_Order) |> SeqDict.fromList
    , pendingOrder = old.pendingOrder |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_PendingOrder) |> SeqDict.fromList
    , expiredOrders = old.expiredOrders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_PendingOrder) |> SeqDict.fromList
    , prices = old.prices |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_Price2) |> SeqDict.fromList
    , time = old.time
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , backendInitialized = old.backendInitialized
    }


migrate_Types_EmailResult : Evergreen.V97.Types.EmailResult -> Evergreen.V102.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V97.Types.SendingEmail ->
            Evergreen.V102.Types.SendingEmail

        Evergreen.V97.Types.EmailSuccess ->
            Evergreen.V102.Types.EmailSuccess

        Evergreen.V97.Types.EmailFailed p0 ->
            Evergreen.V102.Types.EmailFailed p0


migrate_Types_FrontendModel : Evergreen.V97.Types.FrontendModel -> Evergreen.V102.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V97.Types.Loading p0 ->
            Evergreen.V102.Types.Loading (p0 |> migrate_Types_LoadingModel)

        Evergreen.V97.Types.Loaded p0 ->
            Evergreen.V102.Types.Loaded (p0 |> migrate_Types_LoadedModel)


migrate_Types_FrontendMsg : Evergreen.V97.Types.FrontendMsg -> Evergreen.V102.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V97.Types.UrlClicked p0 ->
            Evergreen.V102.Types.UrlClicked p0

        Evergreen.V97.Types.UrlChanged p0 ->
            Evergreen.V102.Types.UrlChanged p0

        Evergreen.V97.Types.Tick p0 ->
            Evergreen.V102.Types.Tick p0

        Evergreen.V97.Types.GotZone p0 ->
            Evergreen.V102.Types.GotZone p0

        Evergreen.V97.Types.GotWindowSize p0 p1 ->
            Evergreen.V102.Types.GotWindowSize p0 p1

        Evergreen.V97.Types.PressedShowTooltip ->
            Evergreen.V102.Types.PressedShowTooltip

        Evergreen.V97.Types.MouseDown ->
            Evergreen.V102.Types.MouseDown

        Evergreen.V97.Types.DownloadTicketSalesReminder ->
            Evergreen.V102.Types.DownloadTicketSalesReminder

        Evergreen.V97.Types.PressedSelectTicket p0 p1 ->
            Evergreen.V102.Types.PressedSelectTicket (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V97.Types.AddAccom p0 ->
            Evergreen.V102.Types.AddAccom (p0 |> migrate_PurchaseForm_Accommodation)

        Evergreen.V97.Types.RemoveAccom p0 ->
            Evergreen.V102.Types.RemoveAccom (p0 |> migrate_PurchaseForm_Accommodation)

        Evergreen.V97.Types.FormChanged p0 ->
            Evergreen.V102.Types.FormChanged (p0 |> migrate_PurchaseForm_PurchaseForm)

        Evergreen.V97.Types.PressedSubmitForm ->
            Evergreen.V102.Types.PressedSubmitForm

        Evergreen.V97.Types.PressedCancelForm ->
            Evergreen.V102.Types.PressedCancelForm

        Evergreen.V97.Types.PressedShowCarbonOffsetTooltip ->
            Evergreen.V102.Types.PressedShowCarbonOffsetTooltip

        Evergreen.V97.Types.SetViewport ->
            Evergreen.V102.Types.SetViewport

        Evergreen.V97.Types.SetViewPortForElement p0 ->
            Evergreen.V102.Types.SetViewPortForElement p0

        Evergreen.V97.Types.AdminPullBackendModel ->
            Evergreen.V102.Types.AdminPullBackendModel

        Evergreen.V97.Types.AdminPullBackendModelResponse p0 ->
            Evergreen.V102.Types.AdminPullBackendModelResponse (p0 |> Result.map migrate_Types_BackendModel)

        Evergreen.V97.Types.Noop ->
            Evergreen.V102.Types.Noop


migrate_Types_InitData2 : Evergreen.V97.Types.InitData2 -> Evergreen.V102.Types.InitData2
migrate_Types_InitData2 old =
    { prices =
        old.prices
            |> SeqDict.toList
            |> List.map
                (Tuple.mapBoth migrate_Id_Id
                    (\rec ->
                        { priceId = rec.priceId |> migrate_Id_Id
                        , price = rec.price |> migrate_Stripe_Price
                        }
                    )
                )
            |> SeqDict.fromList
    , slotsRemaining = old.slotsRemaining |> migrate_Types_TicketAvailability
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    }


migrate_Types_LoadedModel : Evergreen.V97.Types.LoadedModel -> Evergreen.V102.Types.LoadedModel
migrate_Types_LoadedModel old =
    { key = old.key
    , now = old.now
    , zone = old.zone
    , window =
        old.window
            |> (\rec -> rec)
    , prices =
        old.prices
            |> SeqDict.toList
            |> List.map
                (Tuple.mapBoth migrate_Id_Id
                    (\rec ->
                        { priceId = rec.priceId |> migrate_Id_Id
                        , price = rec.price |> migrate_Stripe_Price
                        }
                    )
                )
            |> SeqDict.fromList
    , selectedTicket = old.selectedTicket |> Maybe.map (Tuple.mapBoth migrate_Id_Id migrate_Id_Id)
    , form = old.form |> migrate_PurchaseForm_PurchaseForm
    , route = old.route |> migrate_Route_Route
    , showTooltip = old.showTooltip
    , showCarbonOffsetTooltip = old.showCarbonOffsetTooltip
    , slotsRemaining = old.slotsRemaining |> migrate_Types_TicketAvailability
    , isOrganiser = old.isOrganiser
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , backendModel = old.backendModel |> Maybe.map migrate_Types_BackendModel
    , logoModel = { index = 0 }
    , pressedAudioButton = old.pressedAudioButton
    }


migrate_Types_LoadingModel : Evergreen.V97.Types.LoadingModel -> Evergreen.V102.Types.LoadingModel
migrate_Types_LoadingModel old =
    { key = old.key
    , now = old.now
    , zone = old.zone
    , window = old.window
    , route = old.route |> migrate_Route_Route
    , isOrganiser = old.isOrganiser
    , initData = old.initData |> Maybe.map migrate_Types_InitData2
    }


migrate_Types_Order : Evergreen.V97.Types.Order -> Evergreen.V102.Types.Order
migrate_Types_Order old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , emailResult = old.emailResult |> migrate_Types_EmailResult
    }


migrate_Types_PendingOrder : Evergreen.V97.Types.PendingOrder -> Evergreen.V102.Types.PendingOrder
migrate_Types_PendingOrder old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , sessionId = old.sessionId
    }


migrate_Types_Price2 : Evergreen.V97.Types.Price2 -> Evergreen.V102.Types.Price2
migrate_Types_Price2 old =
    { priceId = old.priceId |> migrate_Id_Id
    , price = old.price |> migrate_Stripe_Price
    }


migrate_Types_TicketAvailability : Evergreen.V97.Types.TicketAvailability -> Evergreen.V102.Types.TicketAvailability
migrate_Types_TicketAvailability old =
    old


migrate_Types_TicketsEnabled : Evergreen.V97.Types.TicketsEnabled -> Evergreen.V102.Types.TicketsEnabled
migrate_Types_TicketsEnabled old =
    case old of
        Evergreen.V97.Types.TicketsEnabled ->
            Evergreen.V102.Types.TicketsEnabled

        Evergreen.V97.Types.TicketsDisabled p0 ->
            Evergreen.V102.Types.TicketsDisabled p0
