module Evergreen.Migrate.V104 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V103.Id
import Evergreen.V103.Internal.Model2
import Evergreen.V103.Internal.Teleport
import Evergreen.V103.Name
import Evergreen.V103.PurchaseForm
import Evergreen.V103.Route
import Evergreen.V103.Stripe
import Evergreen.V103.TravelMode
import Evergreen.V103.Types
import Evergreen.V103.Ui
import Evergreen.V103.View.Logo
import Evergreen.V104.Id
import Evergreen.V104.Internal.Model2
import Evergreen.V104.Internal.Teleport
import Evergreen.V104.Name
import Evergreen.V104.PurchaseForm
import Evergreen.V104.Route
import Evergreen.V104.Stripe
import Evergreen.V104.TravelMode
import Evergreen.V104.Types
import Evergreen.V104.Ui
import Evergreen.V104.View.Logo
import Lamdera.Migrations exposing (..)
import List
import Maybe
import SeqDict


frontendModel : Evergreen.V103.Types.FrontendModel -> ModelMigration Evergreen.V104.Types.FrontendModel Evergreen.V104.Types.FrontendMsg
frontendModel old =
    ModelReset


backendModel : Evergreen.V103.Types.BackendModel -> ModelMigration Evergreen.V104.Types.BackendModel Evergreen.V104.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V103.Types.FrontendMsg -> MsgMigration Evergreen.V104.Types.FrontendMsg Evergreen.V104.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V103.Types.ToBackend -> MsgMigration Evergreen.V104.Types.ToBackend Evergreen.V104.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V103.Types.BackendMsg -> MsgMigration Evergreen.V104.Types.BackendMsg Evergreen.V104.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V103.Types.ToFrontend -> MsgMigration Evergreen.V104.Types.ToFrontend Evergreen.V104.Types.FrontendMsg
toFrontend old =
    MsgUnchanged
