module Evergreen.Migrate.V117 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V114.Animator.Timeline
import Evergreen.V114.EmailAddress
import Evergreen.V114.Fusion
import Evergreen.V114.Fusion.Patch
import Evergreen.V114.Fusion.ValueDict
import Evergreen.V114.Id
import Evergreen.V114.Internal.Model2
import Evergreen.V114.Internal.Teleport
import Evergreen.V114.InternalAnim.Duration
import Evergreen.V114.InternalAnim.Quantity
import Evergreen.V114.InternalAnim.Time
import Evergreen.V114.InternalAnim.Timeline
import Evergreen.V114.Logo
import Evergreen.V114.Name
import Evergreen.V114.NonNegative
import Evergreen.V114.Postmark
import Evergreen.V114.PurchaseForm
import Evergreen.V114.Route
import Evergreen.V114.Stripe
import Evergreen.V114.Theme
import Evergreen.V114.Types
import Evergreen.V114.Ui
import Evergreen.V114.Untrusted
import Evergreen.V117.Animator.Timeline
import Evergreen.V117.EmailAddress
import Evergreen.V117.Fusion
import Evergreen.V117.Fusion.Patch
import Evergreen.V117.Fusion.ValueDict
import Evergreen.V117.Id
import Evergreen.V117.Internal.Model2
import Evergreen.V117.Internal.Teleport
import Evergreen.V117.InternalAnim.Duration
import Evergreen.V117.InternalAnim.Quantity
import Evergreen.V117.InternalAnim.Time
import Evergreen.V117.InternalAnim.Timeline
import Evergreen.V117.Logo
import Evergreen.V117.Name
import Evergreen.V117.NonNegative
import Evergreen.V117.Postmark
import Evergreen.V117.PurchaseForm
import Evergreen.V117.Route
import Evergreen.V117.Stripe
import Evergreen.V117.Theme
import Evergreen.V117.Types
import Evergreen.V117.Ui
import Evergreen.V117.Untrusted
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Quantity
import Result
import SeqDict
import String


frontendModel : Evergreen.V114.Types.FrontendModel -> ModelMigration Evergreen.V117.Types.FrontendModel Evergreen.V117.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V114.Types.BackendModel -> ModelMigration Evergreen.V117.Types.BackendModel Evergreen.V117.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V114.Types.FrontendMsg -> MsgMigration Evergreen.V117.Types.FrontendMsg Evergreen.V117.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V114.Types.ToBackend -> MsgMigration Evergreen.V117.Types.ToBackend Evergreen.V117.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V114.Types.BackendMsg -> MsgMigration Evergreen.V117.Types.BackendMsg Evergreen.V117.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V114.Types.ToFrontend -> MsgMigration Evergreen.V117.Types.ToFrontend Evergreen.V117.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Animator_Timeline_Timeline : (state_old -> state_new) -> Evergreen.V114.Animator.Timeline.Timeline state_old -> Evergreen.V117.Animator.Timeline.Timeline state_new
migrate_Animator_Timeline_Timeline migrate_state old =
    old |> migrate_InternalAnim_Timeline_Timeline migrate_state


migrate_EmailAddress_EmailAddress : Evergreen.V114.EmailAddress.EmailAddress -> Evergreen.V117.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V114.EmailAddress.EmailAddress p0 ->
            Evergreen.V117.EmailAddress.EmailAddress p0


migrate_Fusion_Value : Evergreen.V114.Fusion.Value -> Evergreen.V117.Fusion.Value
migrate_Fusion_Value old =
    case old of
        Evergreen.V114.Fusion.VInt p0 ->
            Evergreen.V117.Fusion.VInt p0

        Evergreen.V114.Fusion.VFloat p0 ->
            Evergreen.V117.Fusion.VFloat p0

        Evergreen.V114.Fusion.VString p0 ->
            Evergreen.V117.Fusion.VString p0

        Evergreen.V114.Fusion.VBool p0 ->
            Evergreen.V117.Fusion.VBool p0

        Evergreen.V114.Fusion.VChar p0 ->
            Evergreen.V117.Fusion.VChar p0

        Evergreen.V114.Fusion.VUnit ->
            Evergreen.V117.Fusion.VUnit

        Evergreen.V114.Fusion.VBytes p0 ->
            Evergreen.V117.Fusion.VBytes p0

        Evergreen.V114.Fusion.VTuple p0 p1 ->
            Evergreen.V117.Fusion.VTuple (p0 |> migrate_Fusion_Value)
                (p1 |> migrate_Fusion_Value)

        Evergreen.V114.Fusion.VTriple p0 p1 p2 ->
            Evergreen.V117.Fusion.VTriple (p0 |> migrate_Fusion_Value)
                (p1 |> migrate_Fusion_Value)
                (p2 |> migrate_Fusion_Value)

        Evergreen.V114.Fusion.VList p0 ->
            Evergreen.V117.Fusion.VList
                { cursor = p0.cursor
                , items = p0.items |> List.map migrate_Fusion_Value
                }

        Evergreen.V114.Fusion.VSet p0 ->
            Evergreen.V117.Fusion.VSet
                { cursor = p0.cursor
                , items = p0.items |> List.map migrate_Fusion_Value
                }

        Evergreen.V114.Fusion.VDict p0 ->
            Evergreen.V117.Fusion.VDict
                { cursor = p0.cursor
                , items = p0.items |> List.map (Tuple.mapBoth migrate_Fusion_Value migrate_Fusion_Value)
                }

        Evergreen.V114.Fusion.VCustom p0 p1 ->
            Evergreen.V117.Fusion.VCustom p0 (p1 |> List.map migrate_Fusion_Value)

        Evergreen.V114.Fusion.VRecord p0 ->
            Evergreen.V117.Fusion.VRecord (p0 |> Dict.map (\k -> migrate_Fusion_Value))

        Evergreen.V114.Fusion.VUnloaded ->
            Evergreen.V117.Fusion.VUnloaded

        Evergreen.V114.Fusion.VPartialString p0 ->
            Evergreen.V117.Fusion.VPartialString p0


migrate_Id_Id : Evergreen.V114.Id.Id a_old -> Evergreen.V117.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V114.Id.Id p0 ->
            Evergreen.V117.Id.Id p0


migrate_InternalAnim_Duration_Duration : Evergreen.V114.InternalAnim.Duration.Duration -> Evergreen.V117.InternalAnim.Duration.Duration
migrate_InternalAnim_Duration_Duration old =
    old |> migrate_InternalAnim_Quantity_Quantity identity


migrate_InternalAnim_Quantity_Quantity : (number_old -> number_new) -> Evergreen.V114.InternalAnim.Quantity.Quantity number_old units_old -> Evergreen.V117.InternalAnim.Quantity.Quantity number_new units_new
migrate_InternalAnim_Quantity_Quantity migrate_number old =
    case old of
        Evergreen.V114.InternalAnim.Quantity.Quantity p0 ->
            Evergreen.V117.InternalAnim.Quantity.Quantity (p0 |> migrate_number)


migrate_InternalAnim_Time_Absolute : Evergreen.V114.InternalAnim.Time.Absolute -> Evergreen.V117.InternalAnim.Time.Absolute
migrate_InternalAnim_Time_Absolute old =
    old |> migrate_InternalAnim_Quantity_Quantity identity


migrate_InternalAnim_Time_Duration : Evergreen.V114.InternalAnim.Time.Duration -> Evergreen.V117.InternalAnim.Time.Duration
migrate_InternalAnim_Time_Duration old =
    old |> migrate_InternalAnim_Duration_Duration


migrate_InternalAnim_Timeline_Event : (event_old -> event_new) -> Evergreen.V114.InternalAnim.Timeline.Event event_old -> Evergreen.V117.InternalAnim.Timeline.Event event_new
migrate_InternalAnim_Timeline_Event migrate_event old =
    case old of
        Evergreen.V114.InternalAnim.Timeline.Event p0 p1 p2 ->
            Evergreen.V117.InternalAnim.Timeline.Event (p0 |> migrate_InternalAnim_Time_Duration)
                (p1 |> migrate_event)
                (p2 |> Maybe.map migrate_InternalAnim_Time_Duration)


migrate_InternalAnim_Timeline_Line : (event_old -> event_new) -> Evergreen.V114.InternalAnim.Timeline.Line event_old -> Evergreen.V117.InternalAnim.Timeline.Line event_new
migrate_InternalAnim_Timeline_Line migrate_event old =
    case old of
        Evergreen.V114.InternalAnim.Timeline.Line p0 p1 p2 ->
            Evergreen.V117.InternalAnim.Timeline.Line (p0 |> migrate_InternalAnim_Time_Absolute)
                (p1 |> migrate_InternalAnim_Timeline_Occurring migrate_event)
                (p2 |> List.map (migrate_InternalAnim_Timeline_Occurring migrate_event))


migrate_InternalAnim_Timeline_Occurring : (event_old -> event_new) -> Evergreen.V114.InternalAnim.Timeline.Occurring event_old -> Evergreen.V117.InternalAnim.Timeline.Occurring event_new
migrate_InternalAnim_Timeline_Occurring migrate_event old =
    case old of
        Evergreen.V114.InternalAnim.Timeline.Occurring p0 p1 p2 ->
            Evergreen.V117.InternalAnim.Timeline.Occurring (p0 |> migrate_event)
                (p1 |> migrate_InternalAnim_Time_Absolute)
                (p2 |> migrate_InternalAnim_Time_Absolute)


migrate_InternalAnim_Timeline_Schedule : (event_old -> event_new) -> Evergreen.V114.InternalAnim.Timeline.Schedule event_old -> Evergreen.V117.InternalAnim.Timeline.Schedule event_new
migrate_InternalAnim_Timeline_Schedule migrate_event old =
    case old of
        Evergreen.V114.InternalAnim.Timeline.Schedule p0 p1 p2 ->
            Evergreen.V117.InternalAnim.Timeline.Schedule (p0 |> migrate_InternalAnim_Time_Duration)
                (p1 |> migrate_InternalAnim_Timeline_Event migrate_event)
                (p2 |> List.map (migrate_InternalAnim_Timeline_Event migrate_event))


migrate_InternalAnim_Timeline_Timeline : (event_old -> event_new) -> Evergreen.V114.InternalAnim.Timeline.Timeline event_old -> Evergreen.V117.InternalAnim.Timeline.Timeline event_new
migrate_InternalAnim_Timeline_Timeline migrate_event old =
    case old of
        Evergreen.V114.InternalAnim.Timeline.Timeline p0 ->
            Evergreen.V117.InternalAnim.Timeline.Timeline (p0 |> migrate_InternalAnim_Timeline_TimelineDetails migrate_event)


migrate_InternalAnim_Timeline_TimelineDetails : (event_old -> event_new) -> Evergreen.V114.InternalAnim.Timeline.TimelineDetails event_old -> Evergreen.V117.InternalAnim.Timeline.TimelineDetails event_new
migrate_InternalAnim_Timeline_TimelineDetails migrate_event old =
    { initial = old.initial |> migrate_event
    , now = old.now |> migrate_InternalAnim_Time_Absolute
    , updatedAt = old.updatedAt |> migrate_InternalAnim_Time_Absolute
    , delay = old.delay |> migrate_InternalAnim_Time_Duration
    , scale = old.scale
    , events = old.events |> migrate_InternalAnim_Timeline_Timetable migrate_event
    , queued = old.queued |> Maybe.map (migrate_InternalAnim_Timeline_Schedule migrate_event)
    , interruption = old.interruption |> List.map (migrate_InternalAnim_Timeline_Schedule migrate_event)
    , running = old.running
    }


migrate_InternalAnim_Timeline_Timetable : (event_old -> event_new) -> Evergreen.V114.InternalAnim.Timeline.Timetable event_old -> Evergreen.V117.InternalAnim.Timeline.Timetable event_new
migrate_InternalAnim_Timeline_Timetable migrate_event old =
    case old of
        Evergreen.V114.InternalAnim.Timeline.Timetable p0 ->
            Evergreen.V117.InternalAnim.Timeline.Timetable (p0 |> List.map (migrate_InternalAnim_Timeline_Line migrate_event))


migrate_Internal_Model2_Msg : Evergreen.V114.Internal.Model2.Msg -> Evergreen.V117.Internal.Model2.Msg
migrate_Internal_Model2_Msg old =
    case old of
        Evergreen.V114.Internal.Model2.Tick p0 ->
            Evergreen.V117.Internal.Model2.Tick p0

        Evergreen.V114.Internal.Model2.Teleported p0 p1 ->
            Evergreen.V117.Internal.Model2.Teleported (p0 |> migrate_Internal_Teleport_Trigger)
                (p1 |> migrate_Internal_Teleport_Event)


migrate_Internal_Model2_State : Evergreen.V114.Internal.Model2.State -> Evergreen.V117.Internal.Model2.State
migrate_Internal_Model2_State old =
    case old of
        Evergreen.V114.Internal.Model2.State p0 ->
            Evergreen.V117.Internal.Model2.State p0


migrate_Internal_Teleport_CssAnimation : Evergreen.V114.Internal.Teleport.CssAnimation -> Evergreen.V117.Internal.Teleport.CssAnimation
migrate_Internal_Teleport_CssAnimation old =
    old


migrate_Internal_Teleport_Data : Evergreen.V114.Internal.Teleport.Data -> Evergreen.V117.Internal.Teleport.Data
migrate_Internal_Teleport_Data old =
    case old of
        Evergreen.V114.Internal.Teleport.Css p0 ->
            Evergreen.V117.Internal.Teleport.Css (p0 |> migrate_Internal_Teleport_CssAnimation)

        Evergreen.V114.Internal.Teleport.ParentTrigger p0 ->
            Evergreen.V117.Internal.Teleport.ParentTrigger (p0 |> migrate_Internal_Teleport_ParentTriggerDetails)


migrate_Internal_Teleport_Event : Evergreen.V114.Internal.Teleport.Event -> Evergreen.V117.Internal.Teleport.Event
migrate_Internal_Teleport_Event old =
    { timestamp = old.timestamp
    , data = old.data |> List.map migrate_Internal_Teleport_Data
    }


migrate_Internal_Teleport_ParentTriggerDetails : Evergreen.V114.Internal.Teleport.ParentTriggerDetails -> Evergreen.V117.Internal.Teleport.ParentTriggerDetails
migrate_Internal_Teleport_ParentTriggerDetails old =
    old


migrate_Internal_Teleport_Trigger : Evergreen.V114.Internal.Teleport.Trigger -> Evergreen.V117.Internal.Teleport.Trigger
migrate_Internal_Teleport_Trigger old =
    case old of
        Evergreen.V114.Internal.Teleport.OnHover ->
            Evergreen.V117.Internal.Teleport.OnHover

        Evergreen.V114.Internal.Teleport.OnRender ->
            Evergreen.V117.Internal.Teleport.OnRender

        Evergreen.V114.Internal.Teleport.OnFocus ->
            Evergreen.V117.Internal.Teleport.OnFocus

        Evergreen.V114.Internal.Teleport.OnFocusWithin ->
            Evergreen.V117.Internal.Teleport.OnFocusWithin

        Evergreen.V114.Internal.Teleport.OnActive ->
            Evergreen.V117.Internal.Teleport.OnActive

        Evergreen.V114.Internal.Teleport.OnDismount ->
            Evergreen.V117.Internal.Teleport.OnDismount


migrate_Logo_Model : Evergreen.V114.Logo.Model -> Evergreen.V117.Logo.Model
migrate_Logo_Model old =
    { index = old.index
    , timeline = old.timeline |> migrate_Animator_Timeline_Timeline migrate_Logo_Tangram
    }


migrate_Logo_Msg : Evergreen.V114.Logo.Msg -> Evergreen.V117.Logo.Msg
migrate_Logo_Msg old =
    case old of
        Evergreen.V114.Logo.ToggleConfig ->
            Evergreen.V117.Logo.ToggleConfig

        Evergreen.V114.Logo.Tick p0 ->
            Evergreen.V117.Logo.Tick p0


migrate_Logo_PieceConfig : Evergreen.V114.Logo.PieceConfig -> Evergreen.V117.Logo.PieceConfig
migrate_Logo_PieceConfig old =
    old


migrate_Logo_Tangram : Evergreen.V114.Logo.Tangram -> Evergreen.V117.Logo.Tangram
migrate_Logo_Tangram old =
    { firstLargeTriangle = old.firstLargeTriangle |> migrate_Logo_PieceConfig
    , secondLargeTriangle = old.secondLargeTriangle |> migrate_Logo_PieceConfig
    , mediumTriangle = old.mediumTriangle |> migrate_Logo_PieceConfig
    , firstSmallTriangle = old.firstSmallTriangle |> migrate_Logo_PieceConfig
    , secondSmallTriangle = old.secondSmallTriangle |> migrate_Logo_PieceConfig
    , square = old.square |> migrate_Logo_PieceConfig
    , parallelogram = old.parallelogram |> migrate_Logo_PieceConfig
    , scale = old.scale
    }


migrate_Name_Name : Evergreen.V114.Name.Name -> Evergreen.V117.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V114.Name.Name p0 ->
            Evergreen.V117.Name.Name p0


migrate_NonNegative_NonNegative : Evergreen.V114.NonNegative.NonNegative -> Evergreen.V117.NonNegative.NonNegative
migrate_NonNegative_NonNegative old =
    case old of
        Evergreen.V114.NonNegative.NonNegative p0 ->
            Evergreen.V117.NonNegative.NonNegative p0


migrate_Postmark_PostmarkError_ : Evergreen.V114.Postmark.PostmarkError_ -> Evergreen.V117.Postmark.PostmarkError_
migrate_Postmark_PostmarkError_ old =
    { errorCode = old.errorCode
    , message = old.message
    , to = old.to |> List.map migrate_EmailAddress_EmailAddress
    }


migrate_Postmark_SendEmailError : Evergreen.V114.Postmark.SendEmailError -> Evergreen.V117.Postmark.SendEmailError
migrate_Postmark_SendEmailError old =
    case old of
        Evergreen.V114.Postmark.UnknownError p0 ->
            Evergreen.V117.Postmark.UnknownError (p0 |> migrate_Postmark_UnknownErrorData)

        Evergreen.V114.Postmark.PostmarkError p0 ->
            Evergreen.V117.Postmark.PostmarkError (p0 |> migrate_Postmark_PostmarkError_)

        Evergreen.V114.Postmark.NetworkError ->
            Evergreen.V117.Postmark.NetworkError

        Evergreen.V114.Postmark.Timeout ->
            Evergreen.V117.Postmark.Timeout

        Evergreen.V114.Postmark.BadUrl p0 ->
            Evergreen.V117.Postmark.BadUrl p0


migrate_Postmark_UnknownErrorData : Evergreen.V114.Postmark.UnknownErrorData -> Evergreen.V117.Postmark.UnknownErrorData
migrate_Postmark_UnknownErrorData old =
    old


migrate_PurchaseForm_AttendeeFormValidated : Evergreen.V114.PurchaseForm.AttendeeFormValidated -> Evergreen.V117.PurchaseForm.AttendeeFormValidated
migrate_PurchaseForm_AttendeeFormValidated old =
    { name = old.name |> migrate_Name_Name
    , country = old.country
    , originCity = old.originCity
    }


migrate_PurchaseForm_PressedSubmit : Evergreen.V114.PurchaseForm.PressedSubmit -> Evergreen.V117.PurchaseForm.PressedSubmit
migrate_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V114.PurchaseForm.PressedSubmit ->
            Evergreen.V117.PurchaseForm.PressedSubmit

        Evergreen.V114.PurchaseForm.NotPressedSubmit ->
            Evergreen.V117.PurchaseForm.NotPressedSubmit


migrate_PurchaseForm_PurchaseForm : Evergreen.V114.PurchaseForm.PurchaseForm -> Evergreen.V117.PurchaseForm.PurchaseForm
migrate_PurchaseForm_PurchaseForm old =
    { submitStatus = old.submitStatus |> migrate_PurchaseForm_SubmitStatus
    , attendees = old.attendees
    , count = old.count |> migrate_PurchaseForm_TicketTypes migrate_NonNegative_NonNegative
    , billingEmail = old.billingEmail
    , grantContribution = old.grantContribution
    }


migrate_PurchaseForm_PurchaseFormValidated : Evergreen.V114.PurchaseForm.PurchaseFormValidated -> Evergreen.V117.PurchaseForm.PurchaseFormValidated
migrate_PurchaseForm_PurchaseFormValidated old =
    { attendees = old.attendees |> List.map migrate_PurchaseForm_AttendeeFormValidated
    , count = old.count |> migrate_PurchaseForm_TicketTypes migrate_NonNegative_NonNegative
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    , grantContribution = old.grantContribution |> migrate_Quantity_Quantity
    }


migrate_PurchaseForm_SubmitStatus : Evergreen.V114.PurchaseForm.SubmitStatus -> Evergreen.V117.PurchaseForm.SubmitStatus
migrate_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V114.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V117.PurchaseForm.NotSubmitted (p0 |> migrate_PurchaseForm_PressedSubmit)

        Evergreen.V114.PurchaseForm.Submitting ->
            Evergreen.V117.PurchaseForm.Submitting

        Evergreen.V114.PurchaseForm.SubmitBackendError p0 ->
            Evergreen.V117.PurchaseForm.SubmitBackendError p0


migrate_PurchaseForm_TicketTypes : (a_old -> a_new) -> Evergreen.V114.PurchaseForm.TicketTypes a_old -> Evergreen.V117.PurchaseForm.TicketTypes a_new
migrate_PurchaseForm_TicketTypes migrate_a old =
    { campfireTicket = old.campfireTicket |> migrate_a
    , singleRoomTicket = old.singleRoomTicket |> migrate_a
    , sharedRoomTicket = old.sharedRoomTicket |> migrate_a
    }


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_Route_Route : Evergreen.V114.Route.Route -> Evergreen.V117.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V114.Route.HomepageRoute ->
            Evergreen.V117.Route.HomepageRoute

        Evergreen.V114.Route.UnconferenceFormatRoute ->
            Evergreen.V117.Route.UnconferenceFormatRoute

        Evergreen.V114.Route.CodeOfConductRoute ->
            Evergreen.V117.Route.CodeOfConductRoute

        Evergreen.V114.Route.ElmCampArchiveRoute ->
            Evergreen.V117.Route.ElmCampArchiveRoute

        Evergreen.V114.Route.AdminRoute p0 ->
            Evergreen.V117.Route.AdminRoute p0

        Evergreen.V114.Route.PaymentSuccessRoute p0 ->
            Evergreen.V117.Route.PaymentSuccessRoute (p0 |> Maybe.map migrate_EmailAddress_EmailAddress)

        Evergreen.V114.Route.PaymentCancelRoute ->
            Evergreen.V117.Route.PaymentCancelRoute

        Evergreen.V114.Route.Camp23Denmark ->
            Evergreen.V117.Route.Camp23Denmark

        Evergreen.V114.Route.Camp24Uk ->
            Evergreen.V117.Route.Camp24Uk

        Evergreen.V114.Route.Camp25US ->
            Evergreen.V117.Route.Camp25US

        Evergreen.V114.Route.TicketPurchaseRoute ->
            Evergreen.V117.Route.TicketPurchaseRoute

        Evergreen.V114.Route.OpportunityGrantRoute ->
            Evergreen.V117.Route.OpportunityGrantRoute


migrate_Stripe_ConversionRateStatus : Evergreen.V114.Stripe.ConversionRateStatus -> Evergreen.V117.Stripe.ConversionRateStatus
migrate_Stripe_ConversionRateStatus old =
    case old of
        Evergreen.V114.Stripe.LoadingConversionRate ->
            Evergreen.V117.Stripe.LoadingConversionRate

        Evergreen.V114.Stripe.LoadedConversionRate p0 ->
            Evergreen.V117.Stripe.LoadedConversionRate (p0 |> SeqDict.map (\k -> migrate_Quantity_Quantity))

        Evergreen.V114.Stripe.LoadingConversionRateFailed p0 ->
            Evergreen.V117.Stripe.LoadingConversionRateFailed p0


migrate_Stripe_Price : Evergreen.V114.Stripe.Price -> Evergreen.V117.Stripe.Price
migrate_Stripe_Price old =
    { priceId = old.priceId |> migrate_Id_Id
    , amount = old.amount |> migrate_Quantity_Quantity
    }


migrate_Theme_Size : Evergreen.V114.Theme.Size -> Evergreen.V117.Theme.Size
migrate_Theme_Size old =
    old


migrate_Types_BackendModel : Evergreen.V114.Types.BackendModel -> Evergreen.V117.Types.BackendModel
migrate_Types_BackendModel old =
    { orders = old.orders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_CompletedOrder) |> SeqDict.fromList
    , pendingOrders = old.pendingOrders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_PendingOrder) |> SeqDict.fromList
    , expiredOrders = old.expiredOrders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_PendingOrder) |> SeqDict.fromList
    , prices = old.prices |> migrate_Types_TicketPriceStatus
    , time = old.time
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , grantApplications = old.grantApplications |> List.map migrate_Types_GrantApplication
    }


migrate_Types_CompletedOrder : Evergreen.V114.Types.CompletedOrder -> Evergreen.V117.Types.CompletedOrder
migrate_Types_CompletedOrder old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , emailResult = old.emailResult |> migrate_Types_EmailResult
    , paymentId = old.paymentId |> migrate_Id_Id
    }


migrate_Types_EmailResult : Evergreen.V114.Types.EmailResult -> Evergreen.V117.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V114.Types.SendingEmail ->
            Evergreen.V117.Types.SendingEmail

        Evergreen.V114.Types.EmailSuccess ->
            Evergreen.V117.Types.EmailSuccess

        Evergreen.V114.Types.EmailFailed p0 ->
            Evergreen.V117.Types.EmailFailed (p0 |> migrate_Postmark_SendEmailError)


migrate_Types_FrontendModel : Evergreen.V114.Types.FrontendModel -> Evergreen.V117.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V114.Types.Loading p0 ->
            Evergreen.V117.Types.Loading (p0 |> migrate_Types_LoadingModel)

        Evergreen.V114.Types.Loaded p0 ->
            Evergreen.V117.Types.Loaded (p0 |> migrate_Types_LoadedModel)


migrate_Types_FrontendMsg : Evergreen.V114.Types.FrontendMsg -> Evergreen.V117.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V114.Types.UrlClicked p0 ->
            Evergreen.V117.Types.UrlClicked p0

        Evergreen.V114.Types.UrlChanged p0 ->
            Evergreen.V117.Types.UrlChanged p0

        Evergreen.V114.Types.Tick p0 ->
            Evergreen.V117.Types.Tick p0

        Evergreen.V114.Types.GotZone p0 ->
            Evergreen.V117.Types.GotZone p0

        Evergreen.V114.Types.GotWindowSize p0 p1 ->
            Evergreen.V117.Types.GotWindowSize p0 p1

        Evergreen.V114.Types.PressedShowTooltip ->
            Evergreen.V117.Types.PressedShowTooltip

        Evergreen.V114.Types.MouseDown ->
            Evergreen.V117.Types.MouseDown

        Evergreen.V114.Types.DownloadTicketSalesReminder ->
            Evergreen.V117.Types.DownloadTicketSalesReminder

        Evergreen.V114.Types.FormChanged p0 ->
            Evergreen.V117.Types.FormChanged (p0 |> migrate_PurchaseForm_PurchaseForm)

        Evergreen.V114.Types.PressedSubmitForm ->
            Evergreen.V117.Types.PressedSubmitForm

        Evergreen.V114.Types.OpportunityGrantFormChanged p0 ->
            Evergreen.V117.Types.OpportunityGrantFormChanged (p0 |> migrate_Types_OpportunityGrantForm)

        Evergreen.V114.Types.PressedSubmitOpportunityGrant ->
            Evergreen.V117.Types.PressedSubmitOpportunityGrant

        Evergreen.V114.Types.SetViewport ->
            Evergreen.V117.Types.SetViewport

        Evergreen.V114.Types.LogoMsg p0 ->
            Evergreen.V117.Types.LogoMsg (p0 |> migrate_Logo_Msg)

        Evergreen.V114.Types.Noop ->
            Evergreen.V117.Types.Noop

        Evergreen.V114.Types.ElmUiMsg p0 ->
            Evergreen.V117.Types.ElmUiMsg (p0 |> migrate_Ui_Msg)

        Evergreen.V114.Types.ScrolledToFragment ->
            Evergreen.V117.Types.ScrolledToFragment

        Evergreen.V114.Types.GotConversionRate p0 ->
            Evergreen.V117.Types.GotConversionRate (p0 |> Result.map (SeqDict.map (\k -> migrate_Quantity_Quantity)))

        Evergreen.V114.Types.SelectedCurrency p0 ->
            Evergreen.V117.Types.SelectedCurrency p0

        Evergreen.V114.Types.FusionPatch p0 ->
            Evergreen.V117.Types.FusionQuery

        Evergreen.V114.Types.FusionQuery ->
            Evergreen.V117.Types.FusionQuery


migrate_Types_GrantApplication : Evergreen.V114.Types.GrantApplication -> Evergreen.V117.Types.GrantApplication
migrate_Types_GrantApplication old =
    { email = old.email |> migrate_EmailAddress_EmailAddress
    , message = old.message
    }


migrate_Types_InitData2 : Evergreen.V114.Types.InitData2 -> Evergreen.V117.Types.InitData2
migrate_Types_InitData2 old =
    { prices =
        old.prices
            |> (\rec ->
                    { campfireTicket = rec.campfireTicket |> migrate_Stripe_Price
                    , singleRoomTicket = rec.singleRoomTicket |> migrate_Stripe_Price
                    , sharedRoomTicket = rec.sharedRoomTicket |> migrate_Stripe_Price
                    }
               )
    , stripeCurrency = old.stripeCurrency
    , ticketsAlreadyPurchased = old.ticketsAlreadyPurchased |> migrate_PurchaseForm_TicketTypes migrate_NonNegative_NonNegative
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , currentCurrency =
        old.currentCurrency
            |> (\rec ->
                    { currency = rec.currency
                    , conversionRate = rec.conversionRate |> migrate_Quantity_Quantity
                    }
               )
    }


migrate_Types_LoadedModel : Evergreen.V114.Types.LoadedModel -> Evergreen.V117.Types.LoadedModel
migrate_Types_LoadedModel old =
    { key = old.key
    , now = old.now
    , timeZone = old.timeZone
    , window = old.window |> migrate_Theme_Size
    , initData = old.initData |> Result.map migrate_Types_InitData2
    , form = old.form |> migrate_PurchaseForm_PurchaseForm
    , opportunityGrantForm = old.opportunityGrantForm |> migrate_Types_OpportunityGrantForm
    , route = old.route |> migrate_Route_Route
    , showTooltip = old.showTooltip
    , backendModel = old.backendModel |> Maybe.map (Tuple.mapBoth migrate_Types_BackendModel migrate_Fusion_Value)
    , logoModel = old.logoModel |> migrate_Logo_Model
    , elmUiState = old.elmUiState |> migrate_Ui_State
    , conversionRate = old.conversionRate |> migrate_Stripe_ConversionRateStatus
    , backendModelJson = Ok ""
    , replaceBackendModelStatus = Evergreen.V117.Types.NotReplacingBackendModel
    , adminPassword = Nothing
    }


migrate_Types_LoadingModel : Evergreen.V114.Types.LoadingModel -> Evergreen.V117.Types.LoadingModel
migrate_Types_LoadingModel old =
    { key = old.key
    , now = old.now
    , timeZone = old.timeZone
    , window = old.window
    , url = old.url
    , isOrganiser = old.isOrganiser
    , initData = old.initData |> Maybe.map (Result.map migrate_Types_InitData2)
    , elmUiState = old.elmUiState |> migrate_Ui_State
    , adminPassword = Nothing
    }


migrate_Types_OpportunityGrantForm : Evergreen.V114.Types.OpportunityGrantForm -> Evergreen.V117.Types.OpportunityGrantForm
migrate_Types_OpportunityGrantForm old =
    { email = old.email
    , message = old.message
    , submitStatus = old.submitStatus |> migrate_Types_OpportunityGrantSubmitStatus
    }


migrate_Types_OpportunityGrantPressedSubmit : Evergreen.V114.Types.OpportunityGrantPressedSubmit -> Evergreen.V117.Types.OpportunityGrantPressedSubmit
migrate_Types_OpportunityGrantPressedSubmit old =
    case old of
        Evergreen.V114.Types.OpportunityGrantPressedSubmit ->
            Evergreen.V117.Types.OpportunityGrantPressedSubmit

        Evergreen.V114.Types.OpportunityGrantNotPressedSubmit ->
            Evergreen.V117.Types.OpportunityGrantNotPressedSubmit


migrate_Types_OpportunityGrantSubmitStatus : Evergreen.V114.Types.OpportunityGrantSubmitStatus -> Evergreen.V117.Types.OpportunityGrantSubmitStatus
migrate_Types_OpportunityGrantSubmitStatus old =
    case old of
        Evergreen.V114.Types.OpportunityGrantNotSubmitted p0 ->
            Evergreen.V117.Types.OpportunityGrantNotSubmitted (p0 |> migrate_Types_OpportunityGrantPressedSubmit)

        Evergreen.V114.Types.OpportunityGrantSubmitting ->
            Evergreen.V117.Types.OpportunityGrantSubmitting

        Evergreen.V114.Types.OpportunityGrantSubmitBackendError p0 ->
            Evergreen.V117.Types.OpportunityGrantSubmitBackendError p0

        Evergreen.V114.Types.OpportunityGrantSubmittedSuccessfully ->
            Evergreen.V117.Types.OpportunityGrantSubmittedSuccessfully


migrate_Types_PendingOrder : Evergreen.V114.Types.PendingOrder -> Evergreen.V117.Types.PendingOrder
migrate_Types_PendingOrder old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , sessionId = old.sessionId
    }


migrate_Types_TicketPriceStatus : Evergreen.V114.Types.TicketPriceStatus -> Evergreen.V117.Types.TicketPriceStatus
migrate_Types_TicketPriceStatus old =
    case old of
        Evergreen.V114.Types.NotLoadingTicketPrices ->
            Evergreen.V117.Types.NotLoadingTicketPrices

        Evergreen.V114.Types.LoadingTicketPrices ->
            Evergreen.V117.Types.LoadingTicketPrices

        Evergreen.V114.Types.LoadedTicketPrices p0 p1 ->
            Evergreen.V117.Types.LoadedTicketPrices p0
                (p1 |> migrate_PurchaseForm_TicketTypes migrate_Stripe_Price)

        Evergreen.V114.Types.FailedToLoadTicketPrices p0 ->
            Evergreen.V117.Types.FailedToLoadTicketPrices p0

        Evergreen.V114.Types.TicketCurrenciesDoNotMatch ->
            Evergreen.V117.Types.TicketCurrenciesDoNotMatch


migrate_Types_TicketsDisabledData : Evergreen.V114.Types.TicketsDisabledData -> Evergreen.V117.Types.TicketsDisabledData
migrate_Types_TicketsDisabledData old =
    old


migrate_Types_TicketsEnabled : Evergreen.V114.Types.TicketsEnabled -> Evergreen.V117.Types.TicketsEnabled
migrate_Types_TicketsEnabled old =
    case old of
        Evergreen.V114.Types.TicketsEnabled ->
            Evergreen.V117.Types.TicketsEnabled

        Evergreen.V114.Types.TicketsDisabled p0 ->
            Evergreen.V117.Types.TicketsDisabled (p0 |> migrate_Types_TicketsDisabledData)


migrate_Types_ToBackend : Evergreen.V114.Types.ToBackend -> Evergreen.V117.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V114.Types.SubmitFormRequest p0 ->
            Evergreen.V117.Types.SubmitFormRequest (p0 |> migrate_Untrusted_Untrusted migrate_PurchaseForm_PurchaseFormValidated)

        Evergreen.V114.Types.CancelPurchaseRequest ->
            Evergreen.V117.Types.CancelPurchaseRequest

        Evergreen.V114.Types.AdminInspect p0 ->
            Evergreen.V117.Types.AdminInspect (Evergreen.V117.Types.AdminPassword p0)

        Evergreen.V114.Types.SubmitOpportunityGrantRequest p0 ->
            Evergreen.V117.Types.SubmitOpportunityGrantRequest (p0 |> migrate_Types_GrantApplication)


migrate_Types_ToFrontend : Evergreen.V114.Types.ToFrontend -> Evergreen.V117.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V114.Types.InitData p0 ->
            Evergreen.V117.Types.InitData (p0 |> Result.map migrate_Types_InitData2)

        Evergreen.V114.Types.SubmitFormResponse p0 ->
            Evergreen.V117.Types.SubmitFormResponse (p0 |> Result.map migrate_Id_Id)

        Evergreen.V114.Types.SlotRemainingChanged p0 ->
            Evergreen.V117.Types.SlotRemainingChanged (p0 |> migrate_PurchaseForm_TicketTypes migrate_NonNegative_NonNegative)

        Evergreen.V114.Types.TicketsEnabledChanged p0 ->
            Evergreen.V117.Types.TicketsEnabledChanged (p0 |> migrate_Types_TicketsEnabled)

        Evergreen.V114.Types.AdminInspectResponse p0 p1 ->
            Evergreen.V117.Types.AdminInspectResponse (p0 |> migrate_Types_BackendModel)
                (p1 |> migrate_Fusion_Value)

        Evergreen.V114.Types.OpportunityGrantSubmitResponse p0 ->
            Evergreen.V117.Types.OpportunityGrantSubmitResponse p0


migrate_Ui_Msg : Evergreen.V114.Ui.Msg -> Evergreen.V117.Ui.Msg
migrate_Ui_Msg old =
    old |> migrate_Internal_Model2_Msg


migrate_Ui_State : Evergreen.V114.Ui.State -> Evergreen.V117.Ui.State
migrate_Ui_State old =
    old |> migrate_Internal_Model2_State


migrate_Untrusted_Untrusted : (a_old -> a_new) -> Evergreen.V114.Untrusted.Untrusted a_old -> Evergreen.V117.Untrusted.Untrusted a_new
migrate_Untrusted_Untrusted migrate_a old =
    case old of
        Evergreen.V114.Untrusted.Untrusted p0 ->
            Evergreen.V117.Untrusted.Untrusted (p0 |> migrate_a)
