module Evergreen.Migrate.V122 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V117.Animator.Timeline
import Evergreen.V117.EmailAddress
import Evergreen.V117.Fusion
import Evergreen.V117.Id
import Evergreen.V117.Internal.Model2
import Evergreen.V117.InternalAnim.Duration
import Evergreen.V117.InternalAnim.Quantity
import Evergreen.V117.InternalAnim.Time
import Evergreen.V117.InternalAnim.Timeline
import Evergreen.V117.Logo
import Evergreen.V117.Name
import Evergreen.V117.NonNegative
import Evergreen.V117.Postmark
import Evergreen.V117.PurchaseForm
import Evergreen.V117.Route
import Evergreen.V117.Stripe
import Evergreen.V117.Theme
import Evergreen.V117.Types
import Evergreen.V117.Ui
import Evergreen.V122.Animator.Timeline
import Evergreen.V122.EmailAddress
import Evergreen.V122.Fusion
import Evergreen.V122.Id
import Evergreen.V122.Internal.Model2
import Evergreen.V122.InternalAnim.Duration
import Evergreen.V122.InternalAnim.Quantity
import Evergreen.V122.InternalAnim.Time
import Evergreen.V122.InternalAnim.Timeline
import Evergreen.V122.Logo
import Evergreen.V122.Name
import Evergreen.V122.NonNegative
import Evergreen.V122.Postmark
import Evergreen.V122.PurchaseForm
import Evergreen.V122.Route
import Evergreen.V122.Stripe
import Evergreen.V122.Theme
import Evergreen.V122.Types
import Evergreen.V122.Ui
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Quantity
import Result
import SeqDict


frontendModel : Evergreen.V117.Types.FrontendModel -> ModelMigration Evergreen.V122.Types.FrontendModel Evergreen.V122.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V117.Types.BackendModel -> ModelMigration Evergreen.V122.Types.BackendModel Evergreen.V122.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V117.Types.FrontendMsg -> MsgMigration Evergreen.V122.Types.FrontendMsg Evergreen.V122.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V117.Types.ToBackend -> MsgMigration Evergreen.V122.Types.ToBackend Evergreen.V122.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V117.Types.BackendMsg -> MsgMigration Evergreen.V122.Types.BackendMsg Evergreen.V122.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V117.Types.ToFrontend -> MsgMigration Evergreen.V122.Types.ToFrontend Evergreen.V122.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Animator_Timeline_Timeline : (state_old -> state_new) -> Evergreen.V117.Animator.Timeline.Timeline state_old -> Evergreen.V122.Animator.Timeline.Timeline state_new
migrate_Animator_Timeline_Timeline migrate_state old =
    old |> migrate_InternalAnim_Timeline_Timeline migrate_state


migrate_EmailAddress_EmailAddress : Evergreen.V117.EmailAddress.EmailAddress -> Evergreen.V122.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V117.EmailAddress.EmailAddress p0 ->
            Evergreen.V122.EmailAddress.EmailAddress p0


migrate_Fusion_Value : Evergreen.V117.Fusion.Value -> Evergreen.V122.Fusion.Value
migrate_Fusion_Value old =
    case old of
        Evergreen.V117.Fusion.VInt p0 ->
            Evergreen.V122.Fusion.VInt p0

        Evergreen.V117.Fusion.VFloat p0 ->
            Evergreen.V122.Fusion.VFloat p0

        Evergreen.V117.Fusion.VString p0 ->
            Evergreen.V122.Fusion.VString p0

        Evergreen.V117.Fusion.VBool p0 ->
            Evergreen.V122.Fusion.VBool p0

        Evergreen.V117.Fusion.VChar p0 ->
            Evergreen.V122.Fusion.VChar p0

        Evergreen.V117.Fusion.VUnit ->
            Evergreen.V122.Fusion.VUnit

        Evergreen.V117.Fusion.VBytes p0 ->
            Evergreen.V122.Fusion.VBytes p0

        Evergreen.V117.Fusion.VTuple p0 p1 ->
            Evergreen.V122.Fusion.VTuple (p0 |> migrate_Fusion_Value)
                (p1 |> migrate_Fusion_Value)

        Evergreen.V117.Fusion.VTriple p0 p1 p2 ->
            Evergreen.V122.Fusion.VTriple (p0 |> migrate_Fusion_Value)
                (p1 |> migrate_Fusion_Value)
                (p2 |> migrate_Fusion_Value)

        Evergreen.V117.Fusion.VList p0 ->
            Evergreen.V122.Fusion.VList
                { cursor = p0.cursor
                , items = p0.items |> List.map migrate_Fusion_Value
                }

        Evergreen.V117.Fusion.VSet p0 ->
            Evergreen.V122.Fusion.VSet
                { cursor = p0.cursor
                , items = p0.items |> List.map migrate_Fusion_Value
                }

        Evergreen.V117.Fusion.VDict p0 ->
            Evergreen.V122.Fusion.VDict
                { cursor = p0.cursor
                , items = p0.items |> List.map (Tuple.mapBoth migrate_Fusion_Value migrate_Fusion_Value)
                }

        Evergreen.V117.Fusion.VCustom p0 p1 ->
            Evergreen.V122.Fusion.VCustom p0 (p1 |> List.map migrate_Fusion_Value)

        Evergreen.V117.Fusion.VRecord p0 ->
            Evergreen.V122.Fusion.VRecord (p0 |> Dict.map (\k -> migrate_Fusion_Value))

        Evergreen.V117.Fusion.VUnloaded ->
            Evergreen.V122.Fusion.VUnloaded

        Evergreen.V117.Fusion.VPartialString p0 ->
            Evergreen.V122.Fusion.VPartialString p0


migrate_Id_Id : Evergreen.V117.Id.Id a_old -> Evergreen.V122.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V117.Id.Id p0 ->
            Evergreen.V122.Id.Id p0


migrate_InternalAnim_Duration_Duration : Evergreen.V117.InternalAnim.Duration.Duration -> Evergreen.V122.InternalAnim.Duration.Duration
migrate_InternalAnim_Duration_Duration old =
    old |> migrate_InternalAnim_Quantity_Quantity identity


migrate_InternalAnim_Quantity_Quantity : (number_old -> number_new) -> Evergreen.V117.InternalAnim.Quantity.Quantity number_old units_old -> Evergreen.V122.InternalAnim.Quantity.Quantity number_new units_new
migrate_InternalAnim_Quantity_Quantity migrate_number old =
    case old of
        Evergreen.V117.InternalAnim.Quantity.Quantity p0 ->
            Evergreen.V122.InternalAnim.Quantity.Quantity (p0 |> migrate_number)


migrate_InternalAnim_Time_Absolute : Evergreen.V117.InternalAnim.Time.Absolute -> Evergreen.V122.InternalAnim.Time.Absolute
migrate_InternalAnim_Time_Absolute old =
    old |> migrate_InternalAnim_Quantity_Quantity identity


migrate_InternalAnim_Time_Duration : Evergreen.V117.InternalAnim.Time.Duration -> Evergreen.V122.InternalAnim.Time.Duration
migrate_InternalAnim_Time_Duration old =
    old |> migrate_InternalAnim_Duration_Duration


migrate_InternalAnim_Timeline_Event : (event_old -> event_new) -> Evergreen.V117.InternalAnim.Timeline.Event event_old -> Evergreen.V122.InternalAnim.Timeline.Event event_new
migrate_InternalAnim_Timeline_Event migrate_event old =
    case old of
        Evergreen.V117.InternalAnim.Timeline.Event p0 p1 p2 ->
            Evergreen.V122.InternalAnim.Timeline.Event (p0 |> migrate_InternalAnim_Time_Duration)
                (p1 |> migrate_event)
                (p2 |> Maybe.map migrate_InternalAnim_Time_Duration)


migrate_InternalAnim_Timeline_Line : (event_old -> event_new) -> Evergreen.V117.InternalAnim.Timeline.Line event_old -> Evergreen.V122.InternalAnim.Timeline.Line event_new
migrate_InternalAnim_Timeline_Line migrate_event old =
    case old of
        Evergreen.V117.InternalAnim.Timeline.Line p0 p1 p2 ->
            Evergreen.V122.InternalAnim.Timeline.Line (p0 |> migrate_InternalAnim_Time_Absolute)
                (p1 |> migrate_InternalAnim_Timeline_Occurring migrate_event)
                (p2 |> List.map (migrate_InternalAnim_Timeline_Occurring migrate_event))


migrate_InternalAnim_Timeline_Occurring : (event_old -> event_new) -> Evergreen.V117.InternalAnim.Timeline.Occurring event_old -> Evergreen.V122.InternalAnim.Timeline.Occurring event_new
migrate_InternalAnim_Timeline_Occurring migrate_event old =
    case old of
        Evergreen.V117.InternalAnim.Timeline.Occurring p0 p1 p2 ->
            Evergreen.V122.InternalAnim.Timeline.Occurring (p0 |> migrate_event)
                (p1 |> migrate_InternalAnim_Time_Absolute)
                (p2 |> migrate_InternalAnim_Time_Absolute)


migrate_InternalAnim_Timeline_Schedule : (event_old -> event_new) -> Evergreen.V117.InternalAnim.Timeline.Schedule event_old -> Evergreen.V122.InternalAnim.Timeline.Schedule event_new
migrate_InternalAnim_Timeline_Schedule migrate_event old =
    case old of
        Evergreen.V117.InternalAnim.Timeline.Schedule p0 p1 p2 ->
            Evergreen.V122.InternalAnim.Timeline.Schedule (p0 |> migrate_InternalAnim_Time_Duration)
                (p1 |> migrate_InternalAnim_Timeline_Event migrate_event)
                (p2 |> List.map (migrate_InternalAnim_Timeline_Event migrate_event))


migrate_InternalAnim_Timeline_Timeline : (event_old -> event_new) -> Evergreen.V117.InternalAnim.Timeline.Timeline event_old -> Evergreen.V122.InternalAnim.Timeline.Timeline event_new
migrate_InternalAnim_Timeline_Timeline migrate_event old =
    case old of
        Evergreen.V117.InternalAnim.Timeline.Timeline p0 ->
            Evergreen.V122.InternalAnim.Timeline.Timeline (p0 |> migrate_InternalAnim_Timeline_TimelineDetails migrate_event)


migrate_InternalAnim_Timeline_TimelineDetails : (event_old -> event_new) -> Evergreen.V117.InternalAnim.Timeline.TimelineDetails event_old -> Evergreen.V122.InternalAnim.Timeline.TimelineDetails event_new
migrate_InternalAnim_Timeline_TimelineDetails migrate_event old =
    { initial = old.initial |> migrate_event
    , now = old.now |> migrate_InternalAnim_Time_Absolute
    , updatedAt = old.updatedAt |> migrate_InternalAnim_Time_Absolute
    , delay = old.delay |> migrate_InternalAnim_Time_Duration
    , scale = old.scale
    , events = old.events |> migrate_InternalAnim_Timeline_Timetable migrate_event
    , queued = old.queued |> Maybe.map (migrate_InternalAnim_Timeline_Schedule migrate_event)
    , interruption = old.interruption |> List.map (migrate_InternalAnim_Timeline_Schedule migrate_event)
    , running = old.running
    }


migrate_InternalAnim_Timeline_Timetable : (event_old -> event_new) -> Evergreen.V117.InternalAnim.Timeline.Timetable event_old -> Evergreen.V122.InternalAnim.Timeline.Timetable event_new
migrate_InternalAnim_Timeline_Timetable migrate_event old =
    case old of
        Evergreen.V117.InternalAnim.Timeline.Timetable p0 ->
            Evergreen.V122.InternalAnim.Timeline.Timetable (p0 |> List.map (migrate_InternalAnim_Timeline_Line migrate_event))


migrate_Internal_Model2_State : Evergreen.V117.Internal.Model2.State -> Evergreen.V122.Internal.Model2.State
migrate_Internal_Model2_State old =
    case old of
        Evergreen.V117.Internal.Model2.State p0 ->
            Evergreen.V122.Internal.Model2.State p0


migrate_Logo_Model : Evergreen.V117.Logo.Model -> Evergreen.V122.Logo.Model
migrate_Logo_Model old =
    { index = old.index
    , timeline = old.timeline |> migrate_Animator_Timeline_Timeline migrate_Logo_Tangram
    }


migrate_Logo_PieceConfig : Evergreen.V117.Logo.PieceConfig -> Evergreen.V122.Logo.PieceConfig
migrate_Logo_PieceConfig old =
    old


migrate_Logo_Tangram : Evergreen.V117.Logo.Tangram -> Evergreen.V122.Logo.Tangram
migrate_Logo_Tangram old =
    { firstLargeTriangle = old.firstLargeTriangle |> migrate_Logo_PieceConfig
    , secondLargeTriangle = old.secondLargeTriangle |> migrate_Logo_PieceConfig
    , mediumTriangle = old.mediumTriangle |> migrate_Logo_PieceConfig
    , firstSmallTriangle = old.firstSmallTriangle |> migrate_Logo_PieceConfig
    , secondSmallTriangle = old.secondSmallTriangle |> migrate_Logo_PieceConfig
    , square = old.square |> migrate_Logo_PieceConfig
    , parallelogram = old.parallelogram |> migrate_Logo_PieceConfig
    , scale = old.scale
    }


migrate_Name_Name : Evergreen.V117.Name.Name -> Evergreen.V122.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V117.Name.Name p0 ->
            Evergreen.V122.Name.Name p0


migrate_NonNegative_NonNegative : Evergreen.V117.NonNegative.NonNegative -> Evergreen.V122.NonNegative.NonNegative
migrate_NonNegative_NonNegative old =
    case old of
        Evergreen.V117.NonNegative.NonNegative p0 ->
            Evergreen.V122.NonNegative.NonNegative p0


migrate_Postmark_PostmarkError_ : Evergreen.V117.Postmark.PostmarkError_ -> Evergreen.V122.Postmark.PostmarkError_
migrate_Postmark_PostmarkError_ old =
    { errorCode = old.errorCode
    , message = old.message
    , to = old.to |> List.map migrate_EmailAddress_EmailAddress
    }


migrate_Postmark_SendEmailError : Evergreen.V117.Postmark.SendEmailError -> Evergreen.V122.Postmark.SendEmailError
migrate_Postmark_SendEmailError old =
    case old of
        Evergreen.V117.Postmark.UnknownError p0 ->
            Evergreen.V122.Postmark.UnknownError (p0 |> migrate_Postmark_UnknownErrorData)

        Evergreen.V117.Postmark.PostmarkError p0 ->
            Evergreen.V122.Postmark.PostmarkError (p0 |> migrate_Postmark_PostmarkError_)

        Evergreen.V117.Postmark.NetworkError ->
            Evergreen.V122.Postmark.NetworkError

        Evergreen.V117.Postmark.Timeout ->
            Evergreen.V122.Postmark.Timeout

        Evergreen.V117.Postmark.BadUrl p0 ->
            Evergreen.V122.Postmark.BadUrl p0


migrate_Postmark_UnknownErrorData : Evergreen.V117.Postmark.UnknownErrorData -> Evergreen.V122.Postmark.UnknownErrorData
migrate_Postmark_UnknownErrorData old =
    old


migrate_PurchaseForm_AttendeeFormValidated : Evergreen.V117.PurchaseForm.AttendeeFormValidated -> Evergreen.V122.PurchaseForm.AttendeeFormValidated
migrate_PurchaseForm_AttendeeFormValidated old =
    { name = old.name |> migrate_Name_Name
    , country = old.country
    , originCity = old.originCity
    }


migrate_PurchaseForm_PressedSubmit : Evergreen.V117.PurchaseForm.PressedSubmit -> Evergreen.V122.PurchaseForm.PressedSubmit
migrate_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V117.PurchaseForm.PressedSubmit ->
            Evergreen.V122.PurchaseForm.PressedSubmit

        Evergreen.V117.PurchaseForm.NotPressedSubmit ->
            Evergreen.V122.PurchaseForm.NotPressedSubmit


migrate_PurchaseForm_PurchaseForm : Evergreen.V117.PurchaseForm.PurchaseForm -> Evergreen.V122.PurchaseForm.PurchaseForm
migrate_PurchaseForm_PurchaseForm old =
    { submitStatus = old.submitStatus |> migrate_PurchaseForm_SubmitStatus
    , attendees = old.attendees
    , count = old.count |> migrate_PurchaseForm_TicketTypes migrate_NonNegative_NonNegative
    , billingEmail = old.billingEmail
    , grantContribution = old.grantContribution
    }


migrate_PurchaseForm_PurchaseFormValidated : Evergreen.V117.PurchaseForm.PurchaseFormValidated -> Evergreen.V122.PurchaseForm.PurchaseFormValidated
migrate_PurchaseForm_PurchaseFormValidated old =
    { attendees = old.attendees |> List.map migrate_PurchaseForm_AttendeeFormValidated
    , count = old.count |> migrate_PurchaseForm_TicketTypes migrate_NonNegative_NonNegative
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    , grantContribution = old.grantContribution |> migrate_Quantity_Quantity
    }


migrate_PurchaseForm_SubmitStatus : Evergreen.V117.PurchaseForm.SubmitStatus -> Evergreen.V122.PurchaseForm.SubmitStatus
migrate_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V117.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V122.PurchaseForm.NotSubmitted (p0 |> migrate_PurchaseForm_PressedSubmit)

        Evergreen.V117.PurchaseForm.Submitting ->
            Evergreen.V122.PurchaseForm.Submitting

        Evergreen.V117.PurchaseForm.SubmitBackendError p0 ->
            Evergreen.V122.PurchaseForm.SubmitBackendError p0


migrate_PurchaseForm_TicketTypes : (a_old -> a_new) -> Evergreen.V117.PurchaseForm.TicketTypes a_old -> Evergreen.V122.PurchaseForm.TicketTypes a_new
migrate_PurchaseForm_TicketTypes migrate_a old =
    { campfireTicket = old.campfireTicket |> migrate_a
    , singleRoomTicket = old.singleRoomTicket |> migrate_a
    , sharedRoomTicket = old.sharedRoomTicket |> migrate_a
    }


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_Route_Route : Evergreen.V117.Route.Route -> Evergreen.V122.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V117.Route.HomepageRoute ->
            Evergreen.V122.Route.HomepageRoute

        Evergreen.V117.Route.UnconferenceFormatRoute ->
            Evergreen.V122.Route.UnconferenceFormatRoute

        Evergreen.V117.Route.CodeOfConductRoute ->
            Evergreen.V122.Route.CodeOfConductRoute

        Evergreen.V117.Route.ElmCampArchiveRoute ->
            Evergreen.V122.Route.ElmCampArchiveRoute

        Evergreen.V117.Route.AdminRoute p0 ->
            Evergreen.V122.Route.AdminRoute p0

        Evergreen.V117.Route.PaymentSuccessRoute p0 ->
            Evergreen.V122.Route.PaymentSuccessRoute (p0 |> Maybe.map migrate_EmailAddress_EmailAddress)

        Evergreen.V117.Route.PaymentCancelRoute ->
            Evergreen.V122.Route.PaymentCancelRoute

        Evergreen.V117.Route.Camp23Denmark ->
            Evergreen.V122.Route.Camp23Denmark

        Evergreen.V117.Route.Camp24Uk ->
            Evergreen.V122.Route.Camp24Uk

        Evergreen.V117.Route.Camp25US ->
            Evergreen.V122.Route.Camp25US

        Evergreen.V117.Route.TicketPurchaseRoute ->
            Evergreen.V122.Route.TicketPurchaseRoute

        Evergreen.V117.Route.OpportunityGrantRoute ->
            Evergreen.V122.Route.OpportunityGrantRoute


migrate_Stripe_ConversionRateStatus : Evergreen.V117.Stripe.ConversionRateStatus -> Evergreen.V122.Stripe.ConversionRateStatus
migrate_Stripe_ConversionRateStatus old =
    case old of
        Evergreen.V117.Stripe.LoadingConversionRate ->
            Evergreen.V122.Stripe.LoadingConversionRate

        Evergreen.V117.Stripe.LoadedConversionRate p0 ->
            Evergreen.V122.Stripe.LoadedConversionRate (p0 |> SeqDict.map (\k -> migrate_Quantity_Quantity))

        Evergreen.V117.Stripe.LoadingConversionRateFailed p0 ->
            Evergreen.V122.Stripe.LoadingConversionRateFailed p0


migrate_Stripe_Price : Evergreen.V117.Stripe.Price -> Evergreen.V122.Stripe.Price
migrate_Stripe_Price old =
    { priceId = old.priceId |> migrate_Id_Id
    , amount = old.amount |> migrate_Quantity_Quantity
    }


migrate_Theme_Size : Evergreen.V117.Theme.Size -> Evergreen.V122.Theme.Size
migrate_Theme_Size old =
    old


migrate_Types_AdminPassword : Evergreen.V117.Types.AdminPassword -> Evergreen.V122.Types.AdminPassword
migrate_Types_AdminPassword old =
    case old of
        Evergreen.V117.Types.AdminPassword p0 ->
            Evergreen.V122.Types.AdminPassword p0


migrate_Types_BackendModel : Evergreen.V117.Types.BackendModel -> Evergreen.V122.Types.BackendModel
migrate_Types_BackendModel old =
    { orders = old.orders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_CompletedOrder) |> SeqDict.fromList
    , pendingOrders = old.pendingOrders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_PendingOrder) |> SeqDict.fromList
    , expiredOrders = old.expiredOrders |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_Id_Id migrate_Types_PendingOrder) |> SeqDict.fromList
    , prices = old.prices |> migrate_Types_TicketPriceStatus
    , time = old.time
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , grantApplications = old.grantApplications |> List.map migrate_Types_GrantApplication
    }


migrate_Types_CompletedOrder : Evergreen.V117.Types.CompletedOrder -> Evergreen.V122.Types.CompletedOrder
migrate_Types_CompletedOrder old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , emailResult = old.emailResult |> migrate_Types_EmailResult
    , paymentId = old.paymentId |> migrate_Id_Id
    }


migrate_Types_EmailResult : Evergreen.V117.Types.EmailResult -> Evergreen.V122.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V117.Types.SendingEmail ->
            Evergreen.V122.Types.SendingEmail

        Evergreen.V117.Types.EmailSuccess ->
            Evergreen.V122.Types.EmailSuccess

        Evergreen.V117.Types.EmailFailed p0 ->
            Evergreen.V122.Types.EmailFailed (p0 |> migrate_Postmark_SendEmailError)


migrate_Types_FrontendModel : Evergreen.V117.Types.FrontendModel -> Evergreen.V122.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V117.Types.Loading p0 ->
            Evergreen.V122.Types.Loading (p0 |> migrate_Types_LoadingModel)

        Evergreen.V117.Types.Loaded p0 ->
            Evergreen.V122.Types.Loaded (p0 |> migrate_Types_LoadedModel)


migrate_Types_GrantApplication : Evergreen.V117.Types.GrantApplication -> Evergreen.V122.Types.GrantApplication
migrate_Types_GrantApplication old =
    { email = old.email |> migrate_EmailAddress_EmailAddress
    , message = old.message
    }


migrate_Types_InitData2 : Evergreen.V117.Types.InitData2 -> Evergreen.V122.Types.InitData2
migrate_Types_InitData2 old =
    { prices =
        old.prices
            |> (\rec ->
                    { campfireTicket = rec.campfireTicket |> migrate_Stripe_Price
                    , singleRoomTicket = rec.singleRoomTicket |> migrate_Stripe_Price
                    , sharedRoomTicket = rec.sharedRoomTicket |> migrate_Stripe_Price
                    }
               )
    , stripeCurrency = old.stripeCurrency
    , ticketsAlreadyPurchased = old.ticketsAlreadyPurchased |> migrate_PurchaseForm_TicketTypes migrate_NonNegative_NonNegative
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , currentCurrency =
        old.currentCurrency
            |> (\rec ->
                    { currency = rec.currency
                    , conversionRate = rec.conversionRate |> migrate_Quantity_Quantity
                    }
               )
    }


migrate_Types_LoadedModel : Evergreen.V117.Types.LoadedModel -> Evergreen.V122.Types.LoadedModel
migrate_Types_LoadedModel old =
    { key = old.key
    , now = old.now
    , timeZone = old.timeZone
    , window = old.window |> migrate_Theme_Size
    , initData = old.initData |> Result.map migrate_Types_InitData2
    , form = old.form |> migrate_PurchaseForm_PurchaseForm
    , opportunityGrantForm = old.opportunityGrantForm |> migrate_Types_OpportunityGrantForm
    , route = old.route |> migrate_Route_Route
    , showTooltip = old.showTooltip
    , backendModel = old.backendModel |> Maybe.map (Tuple.mapBoth migrate_Types_BackendModel migrate_Fusion_Value)
    , logoModel = old.logoModel |> migrate_Logo_Model
    , elmUiState = old.elmUiState |> migrate_Ui_State
    , conversionRate = old.conversionRate |> migrate_Stripe_ConversionRateStatus
    , backendModelJson = old.backendModelJson
    , replaceBackendModelStatus = old.replaceBackendModelStatus |> migrate_Types_ReplaceBackendModelStatus
    , adminPassword = old.adminPassword |> Maybe.map migrate_Types_AdminPassword
    }


migrate_Types_LoadingModel : Evergreen.V117.Types.LoadingModel -> Evergreen.V122.Types.LoadingModel
migrate_Types_LoadingModel old =
    { key = old.key
    , now = old.now
    , timeZone = old.timeZone
    , window = old.window
    , url = old.url
    , isOrganiser = old.isOrganiser
    , initData = old.initData |> Maybe.map (Result.map migrate_Types_InitData2)
    , elmUiState = old.elmUiState |> migrate_Ui_State
    , adminPassword = old.adminPassword |> Maybe.map migrate_Types_AdminPassword
    }


migrate_Types_OpportunityGrantForm : Evergreen.V117.Types.OpportunityGrantForm -> Evergreen.V122.Types.OpportunityGrantForm
migrate_Types_OpportunityGrantForm old =
    { email = old.email
    , message = old.message
    , submitStatus = old.submitStatus |> migrate_Types_OpportunityGrantSubmitStatus
    }


migrate_Types_OpportunityGrantPressedSubmit : Evergreen.V117.Types.OpportunityGrantPressedSubmit -> Evergreen.V122.Types.OpportunityGrantPressedSubmit
migrate_Types_OpportunityGrantPressedSubmit old =
    case old of
        Evergreen.V117.Types.OpportunityGrantPressedSubmit ->
            Evergreen.V122.Types.OpportunityGrantPressedSubmit

        Evergreen.V117.Types.OpportunityGrantNotPressedSubmit ->
            Evergreen.V122.Types.OpportunityGrantNotPressedSubmit


migrate_Types_OpportunityGrantSubmitStatus : Evergreen.V117.Types.OpportunityGrantSubmitStatus -> Evergreen.V122.Types.OpportunityGrantSubmitStatus
migrate_Types_OpportunityGrantSubmitStatus old =
    case old of
        Evergreen.V117.Types.OpportunityGrantNotSubmitted p0 ->
            Evergreen.V122.Types.OpportunityGrantNotSubmitted (p0 |> migrate_Types_OpportunityGrantPressedSubmit)

        Evergreen.V117.Types.OpportunityGrantSubmitting ->
            Evergreen.V122.Types.OpportunityGrantSubmitting

        Evergreen.V117.Types.OpportunityGrantSubmitBackendError p0 ->
            Evergreen.V122.Types.OpportunityGrantSubmitBackendError p0

        Evergreen.V117.Types.OpportunityGrantSubmittedSuccessfully ->
            Evergreen.V122.Types.OpportunityGrantSubmittedSuccessfully


migrate_Types_PendingOrder : Evergreen.V117.Types.PendingOrder -> Evergreen.V122.Types.PendingOrder
migrate_Types_PendingOrder old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , sessionId = old.sessionId
    }


migrate_Types_ReplaceBackendModelStatus : Evergreen.V117.Types.ReplaceBackendModelStatus -> Evergreen.V122.Types.ReplaceBackendModelStatus
migrate_Types_ReplaceBackendModelStatus old =
    case old of
        Evergreen.V117.Types.NotReplacingBackendModel ->
            Evergreen.V122.Types.NotReplacingBackendModel

        Evergreen.V117.Types.ReplacingBackendModel ->
            Evergreen.V122.Types.ReplacingBackendModel

        Evergreen.V117.Types.ReplacedBackendModel ->
            Evergreen.V122.Types.ReplacedBackendModel

        Evergreen.V117.Types.FailedToReplaceBackendModel p0 ->
            Evergreen.V122.Types.FailedToReplaceBackendModel p0


migrate_Types_TicketPriceStatus : Evergreen.V117.Types.TicketPriceStatus -> Evergreen.V122.Types.TicketPriceStatus
migrate_Types_TicketPriceStatus old =
    case old of
        Evergreen.V117.Types.NotLoadingTicketPrices ->
            Evergreen.V122.Types.NotLoadingTicketPrices

        Evergreen.V117.Types.LoadingTicketPrices ->
            Evergreen.V122.Types.LoadingTicketPrices

        Evergreen.V117.Types.LoadedTicketPrices p0 p1 ->
            Evergreen.V122.Types.LoadedTicketPrices p0
                (p1 |> migrate_PurchaseForm_TicketTypes migrate_Stripe_Price)

        Evergreen.V117.Types.FailedToLoadTicketPrices p0 ->
            Evergreen.V122.Types.FailedToLoadTicketPrices p0

        Evergreen.V117.Types.TicketCurrenciesDoNotMatch ->
            Evergreen.V122.Types.TicketCurrenciesDoNotMatch


migrate_Types_TicketsDisabledData : Evergreen.V117.Types.TicketsDisabledData -> Evergreen.V122.Types.TicketsDisabledData
migrate_Types_TicketsDisabledData old =
    old


migrate_Types_TicketsEnabled : Evergreen.V117.Types.TicketsEnabled -> Evergreen.V122.Types.TicketsEnabled
migrate_Types_TicketsEnabled old =
    case old of
        Evergreen.V117.Types.TicketsEnabled ->
            Evergreen.V122.Types.TicketsEnabled

        Evergreen.V117.Types.TicketsDisabled p0 ->
            Evergreen.V122.Types.TicketsDisabled (p0 |> migrate_Types_TicketsDisabledData)


migrate_Ui_State : Evergreen.V117.Ui.State -> Evergreen.V122.Ui.State
migrate_Ui_State old =
    old |> migrate_Internal_Model2_State
