module Evergreen.Migrate.V37 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import Evergreen.V28.EmailAddress
import Evergreen.V28.Id
import Evergreen.V28.Name
import Evergreen.V28.PurchaseForm
import Evergreen.V28.Route
import Evergreen.V28.Stripe
import Evergreen.V28.TravelMode
import Evergreen.V28.Types
import Evergreen.V28.Untrusted
import Evergreen.V37.EmailAddress
import Evergreen.V37.Id
import Evergreen.V37.Name
import Evergreen.V37.PurchaseForm
import Evergreen.V37.Route
import Evergreen.V37.Stripe
import Evergreen.V37.TravelMode
import Evergreen.V37.Types
import Evergreen.V37.Untrusted
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V28.Types.FrontendModel -> ModelMigration Evergreen.V37.Types.FrontendModel Evergreen.V37.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V28.Types.BackendModel -> ModelMigration Evergreen.V37.Types.BackendModel Evergreen.V37.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V28.Types.FrontendMsg -> MsgMigration Evergreen.V37.Types.FrontendMsg Evergreen.V37.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V28.Types.ToBackend -> MsgMigration Evergreen.V37.Types.ToBackend Evergreen.V37.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V28.Types.BackendMsg -> MsgMigration Evergreen.V37.Types.BackendMsg Evergreen.V37.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V28.Types.ToFrontend -> MsgMigration Evergreen.V37.Types.ToFrontend Evergreen.V37.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_EmailAddress_EmailAddress : Evergreen.V28.EmailAddress.EmailAddress -> Evergreen.V37.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V28.EmailAddress.EmailAddress p0 ->
            Evergreen.V37.EmailAddress.EmailAddress p0


migrate_Id_Id : (a_old -> a_new) -> Evergreen.V28.Id.Id a_old -> Evergreen.V37.Id.Id a_new
migrate_Id_Id migrate_a old =
    case old of
        Evergreen.V28.Id.Id p0 ->
            Evergreen.V37.Id.Id p0


migrate_Name_Name : Evergreen.V28.Name.Name -> Evergreen.V37.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V28.Name.Name p0 ->
            Evergreen.V37.Name.Name p0


migrate_PurchaseForm_CouplePurchaseData : Evergreen.V28.PurchaseForm.CouplePurchaseData -> Evergreen.V37.PurchaseForm.CouplePurchaseData
migrate_PurchaseForm_CouplePurchaseData old =
    { attendee1Name = old.attendee1Name |> migrate_Name_Name
    , attendee2Name = old.attendee2Name |> migrate_Name_Name
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> migrate_TravelMode_TravelMode
    , grantContribution = old.grantContribution
    , sponsorship = old.sponsorship
    }


migrate_PurchaseForm_PressedSubmit : Evergreen.V28.PurchaseForm.PressedSubmit -> Evergreen.V37.PurchaseForm.PressedSubmit
migrate_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V28.PurchaseForm.PressedSubmit ->
            Evergreen.V37.PurchaseForm.PressedSubmit

        Evergreen.V28.PurchaseForm.NotPressedSubmit ->
            Evergreen.V37.PurchaseForm.NotPressedSubmit


migrate_PurchaseForm_PurchaseForm : Evergreen.V28.PurchaseForm.PurchaseForm -> Evergreen.V37.PurchaseForm.PurchaseForm
migrate_PurchaseForm_PurchaseForm old =
    { submitStatus = old.submitStatus |> migrate_PurchaseForm_SubmitStatus
    , attendee1Name = old.attendee1Name
    , attendee2Name = old.attendee2Name
    , billingEmail = old.billingEmail
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> Maybe.map migrate_TravelMode_TravelMode
    , grantContribution = old.grantContribution
    , grantApply = old.grantApply
    , sponsorship = old.sponsorship
    }


migrate_PurchaseForm_PurchaseFormValidated : Evergreen.V28.PurchaseForm.PurchaseFormValidated -> Evergreen.V37.PurchaseForm.PurchaseFormValidated
migrate_PurchaseForm_PurchaseFormValidated old =
    case old of
        Evergreen.V28.PurchaseForm.CampfireTicketPurchase p0 ->
            Evergreen.V37.PurchaseForm.CampfireTicketPurchase (p0 |> migrate_PurchaseForm_SinglePurchaseData)

        Evergreen.V28.PurchaseForm.CampTicketPurchase p0 ->
            Evergreen.V37.PurchaseForm.CampTicketPurchase (p0 |> migrate_PurchaseForm_SinglePurchaseData)

        Evergreen.V28.PurchaseForm.CouplesCampTicketPurchase p0 ->
            Evergreen.V37.PurchaseForm.CouplesCampTicketPurchase (p0 |> migrate_PurchaseForm_CouplePurchaseData)


migrate_PurchaseForm_SinglePurchaseData : Evergreen.V28.PurchaseForm.SinglePurchaseData -> Evergreen.V37.PurchaseForm.SinglePurchaseData
migrate_PurchaseForm_SinglePurchaseData old =
    { attendeeName = old.attendeeName |> migrate_Name_Name
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> migrate_TravelMode_TravelMode
    , grantContribution = old.grantContribution
    , sponsorship = old.sponsorship
    }


migrate_PurchaseForm_SubmitStatus : Evergreen.V28.PurchaseForm.SubmitStatus -> Evergreen.V37.PurchaseForm.SubmitStatus
migrate_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V28.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V37.PurchaseForm.NotSubmitted (p0 |> migrate_PurchaseForm_PressedSubmit)

        Evergreen.V28.PurchaseForm.Submitting ->
            Evergreen.V37.PurchaseForm.Submitting

        Evergreen.V28.PurchaseForm.SubmitBackendError p0 ->
            Evergreen.V37.PurchaseForm.SubmitBackendError p0


migrate_Route_Route : Evergreen.V28.Route.Route -> Evergreen.V37.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V28.Route.HomepageRoute ->
            Evergreen.V37.Route.HomepageRoute

        Evergreen.V28.Route.AccessibilityRoute ->
            Evergreen.V37.Route.AccessibilityRoute

        Evergreen.V28.Route.CodeOfConductRoute ->
            Evergreen.V37.Route.CodeOfConductRoute

        Evergreen.V28.Route.PaymentSuccessRoute p0 ->
            Evergreen.V37.Route.PaymentSuccessRoute (p0 |> Maybe.map migrate_EmailAddress_EmailAddress)

        Evergreen.V28.Route.PaymentCancelRoute ->
            Evergreen.V37.Route.PaymentCancelRoute


migrate_Stripe_Price : Evergreen.V28.Stripe.Price -> Evergreen.V37.Stripe.Price
migrate_Stripe_Price old =
    old


migrate_Stripe_PriceId : Evergreen.V28.Stripe.PriceId -> Evergreen.V37.Stripe.PriceId
migrate_Stripe_PriceId old =
    case old of
        Evergreen.V28.Stripe.PriceId p0 ->
            Evergreen.V37.Stripe.PriceId p0


migrate_Stripe_ProductId : Evergreen.V28.Stripe.ProductId -> Evergreen.V37.Stripe.ProductId
migrate_Stripe_ProductId old =
    case old of
        Evergreen.V28.Stripe.ProductId p0 ->
            Evergreen.V37.Stripe.ProductId p0


migrate_Stripe_StripeSessionId : Evergreen.V28.Stripe.StripeSessionId -> Evergreen.V37.Stripe.StripeSessionId
migrate_Stripe_StripeSessionId old =
    case old of
        Evergreen.V28.Stripe.StripeSessionId p0 ->
            Evergreen.V37.Stripe.StripeSessionId p0


migrate_TravelMode_TravelMode : Evergreen.V28.TravelMode.TravelMode -> Evergreen.V37.TravelMode.TravelMode
migrate_TravelMode_TravelMode old =
    case old of
        Evergreen.V28.TravelMode.Flight ->
            Evergreen.V37.TravelMode.Flight

        Evergreen.V28.TravelMode.Bus ->
            Evergreen.V37.TravelMode.Bus

        Evergreen.V28.TravelMode.Car ->
            Evergreen.V37.TravelMode.Car

        Evergreen.V28.TravelMode.Train ->
            Evergreen.V37.TravelMode.Train

        Evergreen.V28.TravelMode.Boat ->
            Evergreen.V37.TravelMode.Boat

        Evergreen.V28.TravelMode.OtherTravelMode ->
            Evergreen.V37.TravelMode.OtherTravelMode


migrate_Types_FrontendModel : Evergreen.V28.Types.FrontendModel -> Evergreen.V37.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V28.Types.Loading p0 ->
            Evergreen.V37.Types.Loading (p0 |> migrate_Types_LoadingModel)

        Evergreen.V28.Types.Loaded p0 ->
            Evergreen.V37.Types.Loaded (p0 |> migrate_Types_LoadedModel)


migrate_Types_InitData2 : Evergreen.V28.Types.InitData2 -> Evergreen.V37.Types.InitData2
migrate_Types_InitData2 old =
    { prices =
        old.prices
            |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_ProductId)
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id migrate_Stripe_PriceId
                    , price = rec.price |> migrate_Stripe_Price
                    }
                )
    , slotsRemaining = old.slotsRemaining |> migrate_Types_TicketAvailability
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    }


migrate_Types_LoadedModel : Evergreen.V28.Types.LoadedModel -> Evergreen.V37.Types.LoadedModel
migrate_Types_LoadedModel old =
    { key = old.key
    , now = old.now
    , window =
        old.window
            |> (\rec -> rec)
    , showTooltip = old.showTooltip
    , prices =
        old.prices
            |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_ProductId)
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id migrate_Stripe_PriceId
                    , price = rec.price |> migrate_Stripe_Price
                    }
                )
    , selectedTicket = old.selectedTicket |> Maybe.map (Tuple.mapBoth (migrate_Id_Id migrate_Stripe_ProductId) (migrate_Id_Id migrate_Stripe_PriceId))
    , form = old.form |> migrate_PurchaseForm_PurchaseForm
    , route = old.route |> migrate_Route_Route
    , showCarbonOffsetTooltip = old.showCarbonOffsetTooltip
    , slotsRemaining = old.slotsRemaining |> migrate_Types_TicketAvailability
    , isOrganiser = old.isOrganiser
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , backendModel = Nothing
    }


migrate_Types_LoadingModel : Evergreen.V28.Types.LoadingModel -> Evergreen.V37.Types.LoadingModel
migrate_Types_LoadingModel old =
    { key = old.key
    , now = old.now
    , window = old.window
    , route = old.route |> migrate_Route_Route
    , isOrganiser = old.isOrganiser
    , initData = old.initData |> Maybe.map migrate_Types_InitData2
    }


migrate_Types_TicketAvailability : Evergreen.V28.Types.TicketAvailability -> Evergreen.V37.Types.TicketAvailability
migrate_Types_TicketAvailability old =
    old


migrate_Types_TicketsEnabled : Evergreen.V28.Types.TicketsEnabled -> Evergreen.V37.Types.TicketsEnabled
migrate_Types_TicketsEnabled old =
    case old of
        Evergreen.V28.Types.TicketsEnabled ->
            Evergreen.V37.Types.TicketsEnabled

        Evergreen.V28.Types.TicketsDisabled p0 ->
            Evergreen.V37.Types.TicketsDisabled p0


migrate_Types_ToBackend : Evergreen.V28.Types.ToBackend -> Evergreen.V37.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V28.Types.SubmitFormRequest p0 p1 ->
            Evergreen.V37.Types.SubmitFormRequest (p0 |> migrate_Id_Id migrate_Stripe_PriceId)
                (p1 |> migrate_Untrusted_Untrusted migrate_PurchaseForm_PurchaseFormValidated)

        Evergreen.V28.Types.CancelPurchaseRequest ->
            Evergreen.V37.Types.CancelPurchaseRequest


migrate_Types_ToFrontend : Evergreen.V28.Types.ToFrontend -> Evergreen.V37.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V28.Types.InitData p0 ->
            Evergreen.V37.Types.InitData (p0 |> migrate_Types_InitData2)

        Evergreen.V28.Types.SubmitFormResponse p0 ->
            Evergreen.V37.Types.SubmitFormResponse (p0 |> Result.map (migrate_Id_Id migrate_Stripe_StripeSessionId))

        Evergreen.V28.Types.SlotRemainingChanged p0 ->
            Evergreen.V37.Types.SlotRemainingChanged (p0 |> migrate_Types_TicketAvailability)

        Evergreen.V28.Types.TicketsEnabledChanged p0 ->
            Evergreen.V37.Types.TicketsEnabledChanged (p0 |> migrate_Types_TicketsEnabled)


migrate_Untrusted_Untrusted : (a_old -> a_new) -> Evergreen.V28.Untrusted.Untrusted a_old -> Evergreen.V37.Untrusted.Untrusted a_new
migrate_Untrusted_Untrusted migrate_a old =
    case old of
        Evergreen.V28.Untrusted.Untrusted p0 ->
            Evergreen.V37.Untrusted.Untrusted (p0 |> migrate_a)
