module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import AssocList
import Evergreen.V3.EmailAddress
import Evergreen.V3.Id
import Evergreen.V3.Name
import Evergreen.V3.Postmark
import Evergreen.V3.PurchaseForm
import Evergreen.V3.Stripe
import Evergreen.V3.TravelMode
import Evergreen.V3.Types
import Evergreen.V6.EmailAddress
import Evergreen.V6.Id
import Evergreen.V6.Name
import Evergreen.V6.Postmark
import Evergreen.V6.PurchaseForm
import Evergreen.V6.Stripe
import Evergreen.V6.TravelMode
import Evergreen.V6.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_EmailAddress_EmailAddress : Evergreen.V3.EmailAddress.EmailAddress -> Evergreen.V6.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V3.EmailAddress.EmailAddress p0 ->
            Evergreen.V6.EmailAddress.EmailAddress p0


migrate_Id_Id : (a_old -> a_new) -> Evergreen.V3.Id.Id a_old -> Evergreen.V6.Id.Id a_new
migrate_Id_Id migrate_a old =
    case old of
        Evergreen.V3.Id.Id p0 ->
            Evergreen.V6.Id.Id p0


migrate_Name_Name : Evergreen.V3.Name.Name -> Evergreen.V6.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V3.Name.Name p0 ->
            Evergreen.V6.Name.Name p0


migrate_Postmark_PostmarkSendResponse : Evergreen.V3.Postmark.PostmarkSendResponse -> Evergreen.V6.Postmark.PostmarkSendResponse
migrate_Postmark_PostmarkSendResponse old =
    old


migrate_PurchaseForm_CouplePurchaseData : Evergreen.V3.PurchaseForm.CouplePurchaseData -> Evergreen.V6.PurchaseForm.CouplePurchaseData
migrate_PurchaseForm_CouplePurchaseData old =
    { attendee1Name = old.attendee1Name |> migrate_Name_Name
    , attendee2Name = old.attendee2Name |> migrate_Name_Name
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> migrate_TravelMode_TravelMode
    }


migrate_PurchaseForm_PurchaseFormValidated : Evergreen.V3.PurchaseForm.PurchaseFormValidated -> Evergreen.V6.PurchaseForm.PurchaseFormValidated
migrate_PurchaseForm_PurchaseFormValidated old =
    case old of
        Evergreen.V3.PurchaseForm.SinglePurchase p0 ->
            Evergreen.V6.PurchaseForm.SinglePurchase (p0 |> migrate_PurchaseForm_SinglePurchaseData)

        Evergreen.V3.PurchaseForm.CouplePurchase p0 ->
            Evergreen.V6.PurchaseForm.CouplePurchase (p0 |> migrate_PurchaseForm_CouplePurchaseData)


migrate_PurchaseForm_SinglePurchaseData : Evergreen.V3.PurchaseForm.SinglePurchaseData -> Evergreen.V6.PurchaseForm.SinglePurchaseData
migrate_PurchaseForm_SinglePurchaseData old =
    { attendeeName = old.attendeeName |> migrate_Name_Name
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> migrate_TravelMode_TravelMode
    }


migrate_Stripe_Price : Evergreen.V3.Stripe.Price -> Evergreen.V6.Stripe.Price
migrate_Stripe_Price old =
    old


migrate_Stripe_PriceId : Evergreen.V3.Stripe.PriceId -> Evergreen.V6.Stripe.PriceId
migrate_Stripe_PriceId old =
    case old of
        Evergreen.V3.Stripe.PriceId p0 ->
            Evergreen.V6.Stripe.PriceId p0


migrate_Stripe_ProductId : Evergreen.V3.Stripe.ProductId -> Evergreen.V6.Stripe.ProductId
migrate_Stripe_ProductId old =
    case old of
        Evergreen.V3.Stripe.ProductId p0 ->
            Evergreen.V6.Stripe.ProductId p0


migrate_Stripe_StripeSessionId : Evergreen.V3.Stripe.StripeSessionId -> Evergreen.V6.Stripe.StripeSessionId
migrate_Stripe_StripeSessionId old =
    case old of
        Evergreen.V3.Stripe.StripeSessionId p0 ->
            Evergreen.V6.Stripe.StripeSessionId p0


migrate_TravelMode_TravelMode : Evergreen.V3.TravelMode.TravelMode -> Evergreen.V6.TravelMode.TravelMode
migrate_TravelMode_TravelMode old =
    case old of
        Evergreen.V3.TravelMode.Flight ->
            Evergreen.V6.TravelMode.Flight

        Evergreen.V3.TravelMode.Bus ->
            Evergreen.V6.TravelMode.Bus

        Evergreen.V3.TravelMode.Car ->
            Evergreen.V6.TravelMode.Car

        Evergreen.V3.TravelMode.Train ->
            Evergreen.V6.TravelMode.Train

        Evergreen.V3.TravelMode.Boat ->
            Evergreen.V6.TravelMode.Boat

        Evergreen.V3.TravelMode.OtherTravelMode ->
            Evergreen.V6.TravelMode.OtherTravelMode


migrate_Types_EmailResult : Evergreen.V3.Types.EmailResult -> Evergreen.V6.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V3.Types.SendingEmail ->
            Evergreen.V6.Types.SendingEmail

        Evergreen.V3.Types.EmailSuccess p0 ->
            Evergreen.V6.Types.EmailSuccess (p0 |> migrate_Postmark_PostmarkSendResponse)

        Evergreen.V3.Types.EmailFailed p0 ->
            Evergreen.V6.Types.EmailFailed p0


migrate_Types_Order : Evergreen.V3.Types.Order -> Evergreen.V6.Types.Order
migrate_Types_Order old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_PriceId
    , submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , emailResult = old.emailResult |> migrate_Types_EmailResult
    }


migrate_Types_PendingOrder : Evergreen.V3.Types.PendingOrder -> Evergreen.V6.Types.PendingOrder
migrate_Types_PendingOrder old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_PriceId
    , submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , sessionId = old.sessionId
    }


migrate_Types_Price2 : Evergreen.V3.Types.Price2 -> Evergreen.V6.Types.Price2
migrate_Types_Price2 old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_PriceId
    , price = old.price |> migrate_Stripe_Price
    }
