module Evergreen.Migrate.V67 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import Audio
import Evergreen.V63.Types
import Evergreen.V67.Types
import Lamdera.Migrations exposing (..)
import Maybe
import Time


frontendModel : Evergreen.V63.Types.FrontendModel -> ModelMigration Evergreen.V67.Types.FrontendModel Evergreen.V67.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V63.Types.BackendModel -> ModelMigration Evergreen.V67.Types.BackendModel Evergreen.V67.Types.BackendMsg
backendModel old =
    ModelMigrated
        ( { orders = AssocList.empty
          , pendingOrder = AssocList.empty
          , expiredOrders = AssocList.empty
          , prices = AssocList.empty
          , time = Time.millisToPosix 0
          , ticketsEnabled = Evergreen.V67.Types.TicketsEnabled
          }
        , Cmd.none
        )


frontendMsg : Evergreen.V63.Types.FrontendMsg -> MsgMigration Evergreen.V67.Types.FrontendMsg Evergreen.V67.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V63.Types.ToBackend -> MsgMigration Evergreen.V67.Types.ToBackend Evergreen.V67.Types.BackendMsg
toBackend old =
    MsgOldValueIgnored


backendMsg : Evergreen.V63.Types.BackendMsg -> MsgMigration Evergreen.V67.Types.BackendMsg Evergreen.V67.Types.BackendMsg
backendMsg old =
    MsgOldValueIgnored


toFrontend : Evergreen.V63.Types.ToFrontend -> MsgMigration Evergreen.V67.Types.ToFrontend Evergreen.V67.Types.FrontendMsg
toFrontend old =
    MsgOldValueIgnored
