module Evergreen.Migrate.V9 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import EmailAddress
import Evergreen.V6.EmailAddress
import Evergreen.V6.Id
import Evergreen.V6.Postmark
import Evergreen.V6.PurchaseForm
import Evergreen.V6.Route
import Evergreen.V6.Stripe
import Evergreen.V6.TravelMode
import Evergreen.V6.Types
import Evergreen.V6.Untrusted
import Evergreen.V9.EmailAddress
import Evergreen.V9.Id
import Evergreen.V9.Postmark
import Evergreen.V9.PurchaseForm
import Evergreen.V9.Route
import Evergreen.V9.Stripe
import Evergreen.V9.TravelMode
import Evergreen.V9.Types
import Evergreen.V9.Untrusted
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V6.Types.FrontendModel -> ModelMigration Evergreen.V9.Types.FrontendModel Evergreen.V9.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V6.Types.BackendModel -> ModelMigration Evergreen.V9.Types.BackendModel Evergreen.V9.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V6.Types.FrontendMsg -> MsgMigration Evergreen.V9.Types.FrontendMsg Evergreen.V9.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V6.Types.ToBackend -> MsgMigration Evergreen.V9.Types.ToBackend Evergreen.V9.Types.BackendMsg
toBackend old =
    MsgOldValueIgnored


backendMsg : Evergreen.V6.Types.BackendMsg -> MsgMigration Evergreen.V9.Types.BackendMsg Evergreen.V9.Types.BackendMsg
backendMsg old =
    MsgOldValueIgnored


toFrontend : Evergreen.V6.Types.ToFrontend -> MsgMigration Evergreen.V9.Types.ToFrontend Evergreen.V9.Types.FrontendMsg
toFrontend old =
    MsgOldValueIgnored


migrate_Types_BackendModel : Evergreen.V6.Types.BackendModel -> Evergreen.V9.Types.BackendModel
migrate_Types_BackendModel old =
    { orders = AssocList.empty
    , pendingOrder = AssocList.empty
    , prices = old.prices |> migrate_AssocList_Dict (migrate_Id_Id migrate_Stripe_ProductId) migrate_Types_Price2
    , time = old.time
    , dummyField = old.dummyField
    }


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_EmailAddress_EmailAddress : Evergreen.V6.EmailAddress.EmailAddress -> Evergreen.V9.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V6.EmailAddress.EmailAddress p0 ->
            Evergreen.V9.EmailAddress.EmailAddress p0


migrate_Id_Id : (a_old -> a_new) -> Evergreen.V6.Id.Id a_old -> Evergreen.V9.Id.Id a_new
migrate_Id_Id migrate_a old =
    case old of
        Evergreen.V6.Id.Id p0 ->
            Evergreen.V9.Id.Id p0


migrate_Postmark_PostmarkSendResponse : Evergreen.V6.Postmark.PostmarkSendResponse -> Evergreen.V9.Postmark.PostmarkSendResponse
migrate_Postmark_PostmarkSendResponse old =
    old


migrate_PurchaseForm_PressedSubmit : Evergreen.V6.PurchaseForm.PressedSubmit -> Evergreen.V9.PurchaseForm.PressedSubmit
migrate_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V6.PurchaseForm.PressedSubmit ->
            Evergreen.V9.PurchaseForm.PressedSubmit

        Evergreen.V6.PurchaseForm.NotPressedSubmit ->
            Evergreen.V9.PurchaseForm.NotPressedSubmit


migrate_PurchaseForm_SubmitStatus : Evergreen.V6.PurchaseForm.SubmitStatus -> Evergreen.V9.PurchaseForm.SubmitStatus
migrate_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V6.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V9.PurchaseForm.NotSubmitted (p0 |> migrate_PurchaseForm_PressedSubmit)

        Evergreen.V6.PurchaseForm.Submitting ->
            Evergreen.V9.PurchaseForm.Submitting

        Evergreen.V6.PurchaseForm.SubmitBackendError ->
            Evergreen.V9.PurchaseForm.SubmitBackendError ""


migrate_Route_Route : Evergreen.V6.Route.Route -> Evergreen.V9.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V6.Route.HomepageRoute ->
            Evergreen.V9.Route.HomepageRoute

        Evergreen.V6.Route.AccessibilityRoute ->
            Evergreen.V9.Route.AccessibilityRoute

        Evergreen.V6.Route.CodeOfConductRoute ->
            Evergreen.V9.Route.CodeOfConductRoute

        Evergreen.V6.Route.PaymentSuccessRoute p0 ->
            Evergreen.V9.Route.PaymentSuccessRoute (p0 |> Maybe.map migrate_EmailAddress_EmailAddress)

        Evergreen.V6.Route.PaymentCancelRoute ->
            Evergreen.V9.Route.PaymentCancelRoute


migrate_Stripe_Price : Evergreen.V6.Stripe.Price -> Evergreen.V9.Stripe.Price
migrate_Stripe_Price old =
    old


migrate_Stripe_PriceData : Evergreen.V6.Stripe.PriceData -> Evergreen.V9.Stripe.PriceData
migrate_Stripe_PriceData old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_PriceId
    , price = old.price |> migrate_Stripe_Price
    , productId = old.productId |> migrate_Id_Id migrate_Stripe_ProductId
    , isActive = old.isActive
    , createdAt = old.createdAt
    }


migrate_Stripe_PriceId : Evergreen.V6.Stripe.PriceId -> Evergreen.V9.Stripe.PriceId
migrate_Stripe_PriceId old =
    case old of
        Evergreen.V6.Stripe.PriceId p0 ->
            Evergreen.V9.Stripe.PriceId p0


migrate_Stripe_ProductId : Evergreen.V6.Stripe.ProductId -> Evergreen.V9.Stripe.ProductId
migrate_Stripe_ProductId old =
    case old of
        Evergreen.V6.Stripe.ProductId p0 ->
            Evergreen.V9.Stripe.ProductId p0


migrate_Stripe_StripeSessionId : Evergreen.V6.Stripe.StripeSessionId -> Evergreen.V9.Stripe.StripeSessionId
migrate_Stripe_StripeSessionId old =
    case old of
        Evergreen.V6.Stripe.StripeSessionId p0 ->
            Evergreen.V9.Stripe.StripeSessionId p0


migrate_TravelMode_TravelMode : Evergreen.V6.TravelMode.TravelMode -> Evergreen.V9.TravelMode.TravelMode
migrate_TravelMode_TravelMode old =
    case old of
        Evergreen.V6.TravelMode.Flight ->
            Evergreen.V9.TravelMode.Flight

        Evergreen.V6.TravelMode.Bus ->
            Evergreen.V9.TravelMode.Bus

        Evergreen.V6.TravelMode.Car ->
            Evergreen.V9.TravelMode.Car

        Evergreen.V6.TravelMode.Train ->
            Evergreen.V9.TravelMode.Train

        Evergreen.V6.TravelMode.Boat ->
            Evergreen.V9.TravelMode.Boat

        Evergreen.V6.TravelMode.OtherTravelMode ->
            Evergreen.V9.TravelMode.OtherTravelMode


migrate_Types_EmailResult : Evergreen.V6.Types.EmailResult -> Evergreen.V9.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V6.Types.SendingEmail ->
            Evergreen.V9.Types.SendingEmail

        Evergreen.V6.Types.EmailSuccess p0 ->
            Evergreen.V9.Types.EmailSuccess (p0 |> migrate_Postmark_PostmarkSendResponse)

        Evergreen.V6.Types.EmailFailed p0 ->
            Evergreen.V9.Types.EmailFailed p0


migrate_Types_Price2 : Evergreen.V6.Types.Price2 -> Evergreen.V9.Types.Price2
migrate_Types_Price2 old =
    { priceId = old.priceId |> migrate_Id_Id migrate_Stripe_PriceId
    , price = old.price |> migrate_Stripe_Price
    }


migrate_Untrusted_Untrusted : (a_old -> a_new) -> Evergreen.V6.Untrusted.Untrusted a_old -> Evergreen.V9.Untrusted.Untrusted a_new
migrate_Untrusted_Untrusted migrate_a old =
    case old of
        Evergreen.V6.Untrusted.Untrusted p0 ->
            Evergreen.V9.Untrusted.Untrusted (p0 |> migrate_a)
