module Evergreen.Migrate.V94 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import Audio
import Evergreen.V85.EmailAddress
import Evergreen.V85.Id
import Evergreen.V85.LiveSchedule
import Evergreen.V85.Name
import Evergreen.V85.Postmark
import Evergreen.V85.PurchaseForm
import Evergreen.V85.Route
import Evergreen.V85.Stripe
import Evergreen.V85.TravelMode
import Evergreen.V85.Types
import Evergreen.V94.EmailAddress
import Evergreen.V94.Id
import Evergreen.V94.LiveSchedule
import Evergreen.V94.Name
import Evergreen.V94.Postmark
import Evergreen.V94.PurchaseForm
import Evergreen.V94.Route
import Evergreen.V94.Stripe
import Evergreen.V94.TravelMode
import Evergreen.V94.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V85.Types.FrontendModel -> ModelMigration Evergreen.V94.Types.FrontendModel Evergreen.V94.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V85.Types.BackendModel -> ModelMigration Evergreen.V94.Types.BackendModel Evergreen.V94.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V85.Types.FrontendMsg -> MsgMigration Evergreen.V94.Types.FrontendMsg Evergreen.V94.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V85.Types.ToBackend -> MsgMigration Evergreen.V94.Types.ToBackend Evergreen.V94.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V85.Types.BackendMsg -> MsgMigration Evergreen.V94.Types.BackendMsg Evergreen.V94.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V85.Types.ToFrontend -> MsgMigration Evergreen.V94.Types.ToFrontend Evergreen.V94.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V85.Types.FrontendModel -> Evergreen.V94.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Audio_Model migrate_Types_FrontendMsg_ migrate_Types_FrontendModel_


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_Audio_Model : (userMsg_old -> userMsg_new) -> (userModel_old -> userModel_new) -> Audio.Model userMsg_old userModel_old -> Audio.Model userMsg_new userModel_new
migrate_Audio_Model migrate_userMsg migrate_userModel old =
    old
        |> Audio.migrateModel migrate_userMsg (\userModel_old -> ( migrate_userModel userModel_old, Cmd.none ))
        |> Tuple.first


migrate_EmailAddress_EmailAddress : Evergreen.V85.EmailAddress.EmailAddress -> Evergreen.V94.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V85.EmailAddress.EmailAddress p0 ->
            Evergreen.V94.EmailAddress.EmailAddress p0


migrate_Id_Id : Evergreen.V85.Id.Id a_old -> Evergreen.V94.Id.Id a_new
migrate_Id_Id old =
    case old of
        Evergreen.V85.Id.Id p0 ->
            Evergreen.V94.Id.Id p0


migrate_LiveSchedule_Msg : Evergreen.V85.LiveSchedule.Msg -> Evergreen.V94.LiveSchedule.Msg
migrate_LiveSchedule_Msg old =
    case old of
        Evergreen.V85.LiveSchedule.PressedAllowAudio ->
            Evergreen.V94.LiveSchedule.PressedAllowAudio


migrate_Name_Name : Evergreen.V85.Name.Name -> Evergreen.V94.Name.Name
migrate_Name_Name old =
    case old of
        Evergreen.V85.Name.Name p0 ->
            Evergreen.V94.Name.Name p0


migrate_Postmark_PostmarkSendResponse : Evergreen.V85.Postmark.PostmarkSendResponse -> Evergreen.V94.Postmark.PostmarkSendResponse
migrate_Postmark_PostmarkSendResponse old =
    old


migrate_PurchaseForm_Accommodation : Evergreen.V85.PurchaseForm.Accommodation -> Evergreen.V94.PurchaseForm.Accommodation
migrate_PurchaseForm_Accommodation old =
    case old of
        Evergreen.V85.PurchaseForm.Offsite ->
            Evergreen.V94.PurchaseForm.Offsite

        Evergreen.V85.PurchaseForm.Campsite ->
            Evergreen.V94.PurchaseForm.Campsite

        Evergreen.V85.PurchaseForm.Single ->
            Evergreen.V94.PurchaseForm.Single

        Evergreen.V85.PurchaseForm.Double ->
            Evergreen.V94.PurchaseForm.Double

        Evergreen.V85.PurchaseForm.Group ->
            Evergreen.V94.PurchaseForm.Group


migrate_PurchaseForm_AttendeeForm : Evergreen.V85.PurchaseForm.AttendeeForm -> Evergreen.V94.PurchaseForm.AttendeeForm
migrate_PurchaseForm_AttendeeForm old =
    { name = old.name
    , email = old.email
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> Maybe.map migrate_TravelMode_TravelMode
    }


migrate_PurchaseForm_AttendeeFormValidated : Evergreen.V85.PurchaseForm.AttendeeFormValidated -> Evergreen.V94.PurchaseForm.AttendeeFormValidated
migrate_PurchaseForm_AttendeeFormValidated old =
    { name = old.name |> migrate_Name_Name
    , email = old.email |> migrate_EmailAddress_EmailAddress
    , country = old.country
    , originCity = old.originCity
    , primaryModeOfTravel = old.primaryModeOfTravel |> Maybe.map migrate_TravelMode_TravelMode
    }


migrate_PurchaseForm_PressedSubmit : Evergreen.V85.PurchaseForm.PressedSubmit -> Evergreen.V94.PurchaseForm.PressedSubmit
migrate_PurchaseForm_PressedSubmit old =
    case old of
        Evergreen.V85.PurchaseForm.PressedSubmit ->
            Evergreen.V94.PurchaseForm.PressedSubmit

        Evergreen.V85.PurchaseForm.NotPressedSubmit ->
            Evergreen.V94.PurchaseForm.NotPressedSubmit


migrate_PurchaseForm_PurchaseForm : Evergreen.V85.PurchaseForm.PurchaseForm -> Evergreen.V94.PurchaseForm.PurchaseForm
migrate_PurchaseForm_PurchaseForm old =
    { submitStatus = old.submitStatus |> migrate_PurchaseForm_SubmitStatus
    , attendees = old.attendees |> List.map migrate_PurchaseForm_AttendeeForm
    , accommodationBookings = old.accommodationBookings |> List.map migrate_PurchaseForm_Accommodation
    , billingEmail = old.billingEmail
    , grantContribution = old.grantContribution
    , grantApply = old.grantApply
    , sponsorship = old.sponsorship
    }


migrate_PurchaseForm_PurchaseFormValidated : Evergreen.V85.PurchaseForm.PurchaseFormValidated -> Evergreen.V94.PurchaseForm.PurchaseFormValidated
migrate_PurchaseForm_PurchaseFormValidated old =
    { attendees = old.attendees |> List.map migrate_PurchaseForm_AttendeeFormValidated
    , accommodationBookings = old.accommodationBookings |> List.map migrate_PurchaseForm_Accommodation
    , billingEmail = old.billingEmail |> migrate_EmailAddress_EmailAddress
    , grantContribution = old.grantContribution
    , grantApply = old.grantApply
    , sponsorship = old.sponsorship
    }


migrate_PurchaseForm_SubmitStatus : Evergreen.V85.PurchaseForm.SubmitStatus -> Evergreen.V94.PurchaseForm.SubmitStatus
migrate_PurchaseForm_SubmitStatus old =
    case old of
        Evergreen.V85.PurchaseForm.NotSubmitted p0 ->
            Evergreen.V94.PurchaseForm.NotSubmitted (p0 |> migrate_PurchaseForm_PressedSubmit)

        Evergreen.V85.PurchaseForm.Submitting ->
            Evergreen.V94.PurchaseForm.Submitting

        Evergreen.V85.PurchaseForm.SubmitBackendError p0 ->
            Evergreen.V94.PurchaseForm.SubmitBackendError p0


migrate_Route_Route : Evergreen.V85.Route.Route -> Evergreen.V94.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V85.Route.HomepageRoute ->
            Evergreen.V94.Route.HomepageRoute

        Evergreen.V85.Route.UnconferenceFormatRoute ->
            Evergreen.V94.Route.UnconferenceFormatRoute

        Evergreen.V85.Route.VenueAndAccessRoute ->
            Evergreen.V94.Route.VenueAndAccessRoute

        Evergreen.V85.Route.CodeOfConductRoute ->
            Evergreen.V94.Route.CodeOfConductRoute

        Evergreen.V85.Route.OrganisersRoute ->
            Evergreen.V94.Route.OrganisersRoute

        Evergreen.V85.Route.ElmCampArchiveRoute ->
            Evergreen.V94.Route.ElmCampArchiveRoute

        Evergreen.V85.Route.AdminRoute p0 ->
            Evergreen.V94.Route.AdminRoute p0

        Evergreen.V85.Route.PaymentSuccessRoute p0 ->
            Evergreen.V94.Route.PaymentSuccessRoute (p0 |> Maybe.map migrate_EmailAddress_EmailAddress)

        Evergreen.V85.Route.PaymentCancelRoute ->
            Evergreen.V94.Route.PaymentCancelRoute

        Evergreen.V85.Route.LiveScheduleRoute ->
            Evergreen.V94.Route.LiveScheduleRoute

        Evergreen.V85.Route.Camp23Denmark p0 ->
            Evergreen.V94.Route.Camp23Denmark (p0 |> migrate_Route_SubPage)

        Evergreen.V85.Route.Camp24Uk p0 ->
            Evergreen.V94.Route.Camp24Uk (p0 |> migrate_Route_SubPage)


migrate_Route_SubPage : Evergreen.V85.Route.SubPage -> Evergreen.V94.Route.SubPage
migrate_Route_SubPage old =
    case old of
        Evergreen.V85.Route.Home ->
            Evergreen.V94.Route.Home

        Evergreen.V85.Route.Artifacts ->
            Evergreen.V94.Route.Artifacts


migrate_Stripe_Price : Evergreen.V85.Stripe.Price -> Evergreen.V94.Stripe.Price
migrate_Stripe_Price old =
    old


migrate_TravelMode_TravelMode : Evergreen.V85.TravelMode.TravelMode -> Evergreen.V94.TravelMode.TravelMode
migrate_TravelMode_TravelMode old =
    case old of
        Evergreen.V85.TravelMode.Flight ->
            Evergreen.V94.TravelMode.Flight

        Evergreen.V85.TravelMode.Bus ->
            Evergreen.V94.TravelMode.Bus

        Evergreen.V85.TravelMode.Car ->
            Evergreen.V94.TravelMode.Car

        Evergreen.V85.TravelMode.Train ->
            Evergreen.V94.TravelMode.Train

        Evergreen.V85.TravelMode.Boat ->
            Evergreen.V94.TravelMode.Boat

        Evergreen.V85.TravelMode.OtherTravelMode ->
            Evergreen.V94.TravelMode.OtherTravelMode


migrate_Types_BackendModel : Evergreen.V85.Types.BackendModel -> Evergreen.V94.Types.BackendModel
migrate_Types_BackendModel old =
    { orders = old.orders |> migrate_AssocList_Dict migrate_Id_Id migrate_Types_Order
    , pendingOrder = old.pendingOrder |> migrate_AssocList_Dict migrate_Id_Id migrate_Types_PendingOrder
    , expiredOrders = old.expiredOrders |> migrate_AssocList_Dict migrate_Id_Id migrate_Types_PendingOrder
    , prices = old.prices |> migrate_AssocList_Dict migrate_Id_Id migrate_Types_Price2
    , time = old.time
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    }


migrate_Types_EmailResult : Evergreen.V85.Types.EmailResult -> Evergreen.V94.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V85.Types.SendingEmail ->
            Evergreen.V94.Types.SendingEmail

        Evergreen.V85.Types.EmailSuccess p0 ->
            Evergreen.V94.Types.EmailSuccess (p0 |> migrate_Postmark_PostmarkSendResponse)

        Evergreen.V85.Types.EmailFailed p0 ->
            Evergreen.V94.Types.EmailFailed p0


migrate_Types_FrontendModel_ : Evergreen.V85.Types.FrontendModel_ -> Evergreen.V94.Types.FrontendModel_
migrate_Types_FrontendModel_ old =
    case old of
        Evergreen.V85.Types.Loading p0 ->
            Evergreen.V94.Types.Loading (p0 |> migrate_Types_LoadingModel)

        Evergreen.V85.Types.Loaded p0 ->
            Evergreen.V94.Types.Loaded (p0 |> migrate_Types_LoadedModel)


migrate_Types_FrontendMsg_ : Evergreen.V85.Types.FrontendMsg_ -> Evergreen.V94.Types.FrontendMsg_
migrate_Types_FrontendMsg_ old =
    case old of
        Evergreen.V85.Types.UrlClicked p0 ->
            Evergreen.V94.Types.UrlClicked p0

        Evergreen.V85.Types.UrlChanged p0 ->
            Evergreen.V94.Types.UrlChanged p0

        Evergreen.V85.Types.Tick p0 ->
            Evergreen.V94.Types.Tick p0

        Evergreen.V85.Types.GotZone p0 ->
            Evergreen.V94.Types.GotZone p0

        Evergreen.V85.Types.GotWindowSize p0 p1 ->
            Evergreen.V94.Types.GotWindowSize p0 p1

        Evergreen.V85.Types.PressedShowTooltip ->
            Evergreen.V94.Types.PressedShowTooltip

        Evergreen.V85.Types.MouseDown ->
            Evergreen.V94.Types.MouseDown

        Evergreen.V85.Types.DownloadTicketSalesReminder ->
            Evergreen.V94.Types.DownloadTicketSalesReminder

        Evergreen.V85.Types.PressedSelectTicket p0 p1 ->
            Evergreen.V94.Types.PressedSelectTicket (p0 |> migrate_Id_Id) (p1 |> migrate_Id_Id)

        Evergreen.V85.Types.AddAccom p0 ->
            Evergreen.V94.Types.AddAccom (p0 |> migrate_PurchaseForm_Accommodation)

        Evergreen.V85.Types.RemoveAccom p0 ->
            Evergreen.V94.Types.RemoveAccom (p0 |> migrate_PurchaseForm_Accommodation)

        Evergreen.V85.Types.FormChanged p0 ->
            Evergreen.V94.Types.FormChanged (p0 |> migrate_PurchaseForm_PurchaseForm)

        Evergreen.V85.Types.PressedSubmitForm ->
            Evergreen.V94.Types.PressedSubmitForm

        Evergreen.V85.Types.PressedCancelForm ->
            Evergreen.V94.Types.PressedCancelForm

        Evergreen.V85.Types.PressedShowCarbonOffsetTooltip ->
            Evergreen.V94.Types.PressedShowCarbonOffsetTooltip

        Evergreen.V85.Types.SetViewport ->
            Evergreen.V94.Types.SetViewport

        Evergreen.V85.Types.LoadedMusic p0 ->
            Evergreen.V94.Types.LoadedMusic p0

        Evergreen.V85.Types.LiveScheduleMsg p0 ->
            Evergreen.V94.Types.LiveScheduleMsg (p0 |> migrate_LiveSchedule_Msg)

        Evergreen.V85.Types.SetViewPortForElement p0 ->
            Evergreen.V94.Types.SetViewPortForElement p0

        Evergreen.V85.Types.AdminPullBackendModel ->
            Evergreen.V94.Types.AdminPullBackendModel

        Evergreen.V85.Types.AdminPullBackendModelResponse p0 ->
            Evergreen.V94.Types.AdminPullBackendModelResponse (p0 |> Result.map migrate_Types_BackendModel)

        Evergreen.V85.Types.Noop ->
            Evergreen.V94.Types.Noop


migrate_Types_InitData2 : Evergreen.V85.Types.InitData2 -> Evergreen.V94.Types.InitData2
migrate_Types_InitData2 old =
    { prices =
        old.prices
            |> migrate_AssocList_Dict migrate_Id_Id
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id
                    , price = rec.price |> migrate_Stripe_Price
                    }
                )
    , slotsRemaining = old.slotsRemaining |> migrate_Types_TicketAvailability
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    }


migrate_Types_LoadedModel : Evergreen.V85.Types.LoadedModel -> Evergreen.V94.Types.LoadedModel
migrate_Types_LoadedModel old =
    { key = old.key
    , now = old.now
    , zone = old.zone
    , window =
        old.window
            |> (\rec -> rec)
    , prices =
        old.prices
            |> migrate_AssocList_Dict migrate_Id_Id
                (\rec ->
                    { priceId = rec.priceId |> migrate_Id_Id
                    , price = rec.price |> migrate_Stripe_Price
                    }
                )
    , selectedTicket = old.selectedTicket |> Maybe.map (Tuple.mapBoth migrate_Id_Id migrate_Id_Id)
    , form = old.form |> migrate_PurchaseForm_PurchaseForm
    , route = old.route |> migrate_Route_Route
    , showTooltip = old.showTooltip
    , showCarbonOffsetTooltip = old.showCarbonOffsetTooltip
    , slotsRemaining = old.slotsRemaining |> migrate_Types_TicketAvailability
    , isOrganiser = old.isOrganiser
    , ticketsEnabled = old.ticketsEnabled |> migrate_Types_TicketsEnabled
    , backendModel = old.backendModel |> Maybe.map migrate_Types_BackendModel
    , audio = old.audio
    , pressedAudioButton = old.pressedAudioButton
    }


migrate_Types_LoadingModel : Evergreen.V85.Types.LoadingModel -> Evergreen.V94.Types.LoadingModel
migrate_Types_LoadingModel old =
    { key = old.key
    , now = old.now
    , zone = old.zone
    , window = old.window
    , route = old.route |> migrate_Route_Route
    , isOrganiser = old.isOrganiser
    , initData = old.initData |> Maybe.map migrate_Types_InitData2
    , audio = old.audio
    }


migrate_Types_Order : Evergreen.V85.Types.Order -> Evergreen.V94.Types.Order
migrate_Types_Order old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , emailResult = old.emailResult |> migrate_Types_EmailResult
    }


migrate_Types_PendingOrder : Evergreen.V85.Types.PendingOrder -> Evergreen.V94.Types.PendingOrder
migrate_Types_PendingOrder old =
    { submitTime = old.submitTime
    , form = old.form |> migrate_PurchaseForm_PurchaseFormValidated
    , sessionId = old.sessionId
    }


migrate_Types_Price2 : Evergreen.V85.Types.Price2 -> Evergreen.V94.Types.Price2
migrate_Types_Price2 old =
    { priceId = old.priceId |> migrate_Id_Id
    , price = old.price |> migrate_Stripe_Price
    }


migrate_Types_TicketAvailability : Evergreen.V85.Types.TicketAvailability -> Evergreen.V94.Types.TicketAvailability
migrate_Types_TicketAvailability old =
    old


migrate_Types_TicketsEnabled : Evergreen.V85.Types.TicketsEnabled -> Evergreen.V94.Types.TicketsEnabled
migrate_Types_TicketsEnabled old =
    case old of
        Evergreen.V85.Types.TicketsEnabled ->
            Evergreen.V94.Types.TicketsEnabled

        Evergreen.V85.Types.TicketsDisabled p0 ->
            Evergreen.V94.Types.TicketsDisabled p0
